//! The web-chat agent's tool-schema artifact (issue #354, ADR-0054 §3) — the THIRD door.
//!
//! ADR-0052 §5 fixed "contract types live OS-free in core, one schema, many doors": native MCP
//! and the in-page JS layer both derive from `reuben-core`. This module is the third derivation —
//! the schemas the hosted proxy declares to the model. It emits ONE JSON artifact
//! (`js/tool-schemas.generated.json`) that BOTH consumers read:
//!
//!   - the proxy (`proxy/relay.mjs`) puts `tools[*].{name,description,input_schema}` in every
//!     Anthropic request and `instrument_schema` in the model's grounding, and
//!   - the in-page layer (`js/tools.mjs` via `createToolLayer`) EXECUTES those exact eight names.
//!
//! The declared contract and the executed contract therefore cannot drift (proven two ways: the
//! Rust staleness test below, and `js/tool-schemas.test.mjs` asserting the executed tool names
//! match the artifact).
//!
//! The CORE-TYPED seam is `instrument_schema`: the instrument-document JSON Schema generated by
//! [`reuben_core::schema::generate`] from the operator registry — the SAME generator the native
//! `reuben://schema/instrument` resource and the committed `crates/reuben-core/schema/…` file use.
//! It cannot drift from the operator set because it is generated from it. The eight tool INPUT
//! shapes are thin JS-only wrappers (`{document}`, `{messages}`, `{expect}`, `{name}`) that mirror
//! the `createToolLayer` function signatures (ADR-0048 §5) — hand-declared here as `json!` literals
//! because they have no core serde type to derive from (the native lane's `SwapParams`/`SendParams`
//! live in `reuben-mcp` and are path-based, not the web lane's by-value shapes; ADR-0052 §2).
//!
//! Regenerate after changing an operator, the instrument format, or a tool's input shape:
//!   `cargo run --example gen_tool_schemas` (from `crates/reuben-web`)
//! The `committed_artifact_is_in_sync` test fails if the committed file is stale.

use serde_json::{json, Value};

use reuben_core::registry::Registry;
use reuben_core::schema;

/// A generic instrument-document input: any JSON object, grounded by `instrument_schema` (carried
/// once at the artifact root and surfaced to the model out-of-band, exactly as the native lane
/// serves `reuben://schema/instrument` separately rather than inlining it per tool — ADR-0048 §7).
/// The engine is the single validation authority; the schema is grounding, not a gate.
fn document_input(role: &str) -> Value {
    json!({
        "type": "object",
        "description": format!(
            "The reuben instrument document {role}, as a JSON object conforming to the \
             instrument schema (see `instrument_schema`)."
        ),
    })
}

/// Build the eight-tool schema artifact (issue #354, ADR-0054 §3). Deterministic: a pure function
/// of `Registry::builtin()`, so the committed copy can be staleness-checked.
///
/// Shape:
/// ```jsonc
/// {
///   "$comment": "generated — do not edit",
///   "model_default": "claude-sonnet-5",   // ADR-0054 §4: the tier is the decision, id is config
///   "instrument_schema": { … },           // CORE-generated document schema (the no-drift seam)
///   "tools": [ { "name", "description", "input_schema" }, … × 8 ]
/// }
/// ```
pub fn generate() -> Value {
    let instrument_schema = schema::generate(&Registry::builtin());

    // The eight ADR-0048 contracts, in the ADR-0052 §2 / spec §0.2 table order (…send, swap,
    // engine_status…). Array order is irrelevant to the model, and both no-drift tests sort before
    // comparing, so this is presentation only. `input_schema` is the EXECUTED shape from
    // `createToolLayer` (js/tools.mjs): web `swap`/`describe_instrument`/`validate` take a document
    // BY VALUE (ADR-0052 §2), not the native path-based inputs. Descriptions are model-facing
    // (never user-visible), so they speak engine vocabulary — the spec §1 lexicon gate governs only
    // user-facing copy.
    let tools = json!([
        {
            "name": "describe_operators",
            "description": "List the registered operators and their ports/params. Omit `name` to \
                            list the whole registry; pass a `name` to describe one operator. An \
                            unknown name is an error (the tool could not do its job).",
            "input_schema": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Restrict to one operator type; omit for the full registry."
                    }
                },
                "additionalProperties": false
            }
        },
        {
            "name": "describe_instrument",
            "description": "Describe an instrument document's boundary (inputs/outputs) as a host \
                            will see it. A document that fails to load has no boundary — that is an \
                            error; run `validate` for the full report.",
            "input_schema": {
                "type": "object",
                "properties": { "document": document_input("to describe") },
                "required": ["document"],
                "additionalProperties": false
            }
        },
        {
            "name": "validate",
            "description": "Validate an instrument document (load + instantiate) and return a \
                            report of errors and warnings. A failing validation is a SUCCESSFUL \
                            result carrying `{ok:false, errors, warnings}` — not an error.",
            "input_schema": {
                "type": "object",
                "properties": { "document": document_input("to validate") },
                "required": ["document"],
                "additionalProperties": false
            }
        },
        {
            "name": "send",
            "description": "Dispatch a batch of control messages to audition a change on the live \
                            engine WITHOUT reshaping the document (ADR-0048 §5). Ephemeral: these \
                            values live in render state only and are clobbered at the next swap. \
                            At least one message is required.",
            "input_schema": {
                "type": "object",
                "properties": {
                    "messages": {
                        "type": "array",
                        "minItems": 1,
                        "description": "The control messages to dispatch, in order (at least one).",
                        "items": {
                            "type": "object",
                            "properties": {
                                "address": {
                                    "type": "string",
                                    "description": "The full control address, e.g. `/voice1/cutoff`."
                                },
                                "args": {
                                    "type": "array",
                                    "description": "The arguments — numbers or strings.",
                                    "items": { "type": ["number", "string"] }
                                }
                            },
                            "required": ["address"],
                            "additionalProperties": false
                        }
                    }
                },
                "required": ["messages"],
                "additionalProperties": false
            }
        },
        {
            "name": "swap",
            "description": "Install an instrument document BY VALUE as the playing engine (ADR-0052 \
                            §2). This is a restart-swap: every node is rebuilt cold, so the diff \
                            reports survived:0. Returns the validation report + content_hash + (on \
                            success) a structural node-identity diff. An `ok:false` report installs \
                            nothing and the old sound keeps playing. Pass `expect` (a content_hash) \
                            to guard against a stale swap — a mismatch returns a conflict, no install.",
            "input_schema": {
                "type": "object",
                "properties": {
                    "document": document_input("to install"),
                    "resources": {
                        "type": "array",
                        "description": "Resources the document references, supplied by value \
                                        (there is no disk on the web lane).",
                        "items": { "type": "object" }
                    },
                    "expect": {
                        "type": "string",
                        "description": "The content_hash the client believes is installed; a \
                                        mismatch rejects the swap (ADR-0046 §9)."
                    }
                },
                "required": ["document"],
                "additionalProperties": false
            }
        },
        {
            "name": "engine_status",
            "description": "Report whether the engine is reachable and the AudioContext state. \
                            Never an error — answering \"reachable?\" is its job.",
            "input_schema": { "type": "object", "properties": {}, "additionalProperties": false }
        },
        {
            "name": "get_current_instrument",
            "description": "Return the document the engine is currently playing, with its \
                            content_hash (the token a later swap's `expect` guard compares). \
                            Nothing loaded is an error.",
            "input_schema": { "type": "object", "properties": {}, "additionalProperties": false }
        },
        {
            "name": "get_diagnostics",
            "description": "Return the engine's running diagnostics counters (output_xruns plus the \
                            input-ring under/over/producer-drop counts).",
            "input_schema": { "type": "object", "properties": {}, "additionalProperties": false }
        }
    ]);

    json!({
        "$comment": "GENERATED by `cargo run --example gen_tool_schemas` (issue #354, ADR-0054 §3). \
                     Do not edit by hand. Consumed by BOTH proxy/relay.mjs (declares to the model) \
                     and js/tools.mjs (executes). `instrument_schema` is generated from reuben-core.",
        "model_default": "claude-sonnet-5",
        "instrument_schema": instrument_schema,
        "tools": tools
    })
}

/// The artifact as pretty JSON with a trailing newline — the committed on-disk form.
pub fn generate_pretty() -> String {
    let mut s = serde_json::to_string_pretty(&generate()).expect("artifact serializes");
    s.push('\n');
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed artifact must equal a fresh generation, or the proxy would declare a schema
    /// the generator no longer produces (ADR-0054 §3's whole point). Regenerate with the example.
    #[test]
    fn committed_artifact_is_in_sync() {
        let committed = include_str!("../js/tool-schemas.generated.json");
        assert_eq!(
            committed,
            generate_pretty(),
            "js/tool-schemas.generated.json is stale — run `cargo run --example gen_tool_schemas`"
        );
    }

    #[test]
    fn declares_exactly_the_eight_adr_0048_contracts() {
        let artifact = generate();
        let names: Vec<&str> = artifact["tools"]
            .as_array()
            .expect("tools array")
            .iter()
            .map(|t| t["name"].as_str().expect("tool name"))
            .collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        assert_eq!(
            sorted,
            [
                "describe_instrument",
                "describe_operators",
                "engine_status",
                "get_current_instrument",
                "get_diagnostics",
                "send",
                "swap",
                "validate",
            ],
            "the artifact must declare exactly the ADR-0048 §1 roster"
        );
    }

    #[test]
    fn instrument_schema_is_the_core_generated_schema() {
        // The no-drift seam: `instrument_schema` is byte-for-byte the core generator's output, so
        // the model authors against the SAME schema the engine validates against.
        let artifact = generate();
        assert_eq!(
            artifact["instrument_schema"],
            schema::generate(&Registry::builtin()),
            "instrument_schema must be the core-generated document schema, not a hand-copy"
        );
    }

    #[test]
    fn every_tool_input_schema_is_an_object() {
        // The Anthropic tools API requires each `input_schema` to be an object schema.
        let artifact = generate();
        for tool in artifact["tools"].as_array().unwrap() {
            assert_eq!(
                tool["input_schema"]["type"],
                json!("object"),
                "tool {} input_schema must be an object",
                tool["name"]
            );
        }
    }

    #[test]
    fn is_deterministic() {
        assert_eq!(generate_pretty(), generate_pretty());
    }
}
