//! `add` — `out = a + b`, per sample (ADR-0029, ADR-0017, ADR-0033).
//!
//! The sanctioned way to **combine two streams additively**: base-plus-modulation is an explicit
//! `add`. A dense `Float`→`Float` op — both operands are materialized `Float` inputs whose unwired
//! default is the additive identity `0`, so wiring only one side passes it through unchanged
//! (ADR-0028 materialize fills the other with zeros). One of the math family's pointwise members;
//! its arithmetic is the generic [`add_fn`], called once per sample by the generated signal shell
//! and once per change by the value shell (the scalar-fn + shell seam — issue #83).
//!
//! Both carriers are generated by [`number_operator_contract!`](crate::number_operator_contract)
//! (ADR-0033): `AddF32Signal` (per-sample buffers) and `AddF32Value` (held scalars), each with the
//! additive identity `0` as its operands' unwired default.
//!
//! - input 0: `a` (`Float`) — first operand. Unwired default `0`.
//! - input 1: `b` (`Float`) — second operand. Unwired default `0`.
//! - output 0: `out` — `a + b`.

/// The op's scalar math, written once (ADR-0029 pure-fn seam) and generic over the number type so
/// the macro can instantiate it per `numbers` entry (`f32` today). A future sparse/`Note`-field
/// shell (issue #83) reuses this rather than re-deriving the arithmetic.
#[inline]
fn add_fn<T: core::ops::Add<Output = T>>(a: T, b: T) -> T {
    a + b
}

// One declaration -> AddF32Value + AddF32Signal, each with its contract, Operator impl,
// registration, and a defaults-are-data test (ADR-0033). The additive identity `0` is the operands'
// unwired default, so wiring only one side passes it through (ADR-0029). Port names `a`/`b` are
// preserved from the hand-written contract, so existing instrument wiring is untouched.
crate::number_operator_contract!(Add {
    numbers:  [f32],
    carriers: [value, signal],
    inputs:   { a: number { default 0.0 }, b: number { default 0.0 } },
    outputs:  { out },
    function: add_fn(a, b),
});

#[cfg(test)]
mod tests {
    use super::add_f32_signal::{self, AddF32Signal};
    use super::add_f32_value::{self, AddF32Value};
    use crate::operators::math_test::{signal_out, value_emits};

    /// Drive the signal form through the real engine; returns `out`. `Some(buf)` drives a buffer,
    /// `None` leaves the port unwired so the engine materializes its additive-identity default `0`.
    fn sig(a: Option<&[f32]>, b: Option<&[f32]>, n: usize) -> Vec<f32> {
        signal_out(AddF32Signal::new(), add_f32_signal::OUT_OUT, n, |d| {
            if let Some(a) = a {
                d.drive(add_f32_signal::IN_A, a);
            }
            if let Some(b) = b {
                d.drive(add_f32_signal::IN_B, b);
            }
        })
    }

    /// Drive the value form; returns the emitted sum(s). `None` leaves the operand at its default.
    fn val(a: Option<f32>, b: Option<f32>) -> Vec<f32> {
        value_emits(AddF32Value::new(), |d| {
            if let Some(a) = a {
                d.set(add_f32_value::IN_A, a);
            }
            if let Some(b) = b {
                d.set(add_f32_value::IN_B, b);
            }
        })
    }

    #[test]
    fn sums_two_buffers() {
        let a = [1.0, 2.0, 3.0];
        let b = [10.0, 20.0, 30.0];
        assert_eq!(sig(Some(&a), Some(&b), 3), vec![11.0, 22.0, 33.0]);
    }

    #[test]
    fn unwired_b_passes_a_through() {
        // Additive identity 0: wiring only `in_a` leaves it unchanged (base-plus-modulation).
        let a = [5.0, 6.0, 7.0];
        assert_eq!(sig(Some(&a), None, 3), vec![5.0, 6.0, 7.0]);
    }

    #[test]
    fn sums_held_operands() {
        assert_eq!(val(Some(3.0), Some(4.0)), vec![7.0]);
    }

    #[test]
    fn unwired_b_passes_held_a_through() {
        // Additive identity 0: wiring only `in_a` emits it unchanged.
        assert_eq!(val(Some(5.0), None), vec![5.0]);
    }
}
