//! `div` — `out = a / b`, per sample.
//!
//! The sanctioned way to **divide one stream by another**: ratios, normalisation, reciprocal
//! scaling. A dense `Float`→`Float` op — `b`'s unwired default is the multiplicative identity `1`,
//! so wiring only `a` passes it through unchanged (an unwired Value materializes to its default at
//! the Signal input). Its arithmetic is the f32 [`div_fn`], called once per sample by the
//! signal shell and once per change by the value shell (issue #83).
//!
//! Division by zero would yield `±inf`/`NaN` (or panic, for integers) and poison the audio graph, so
//! [`div_fn`] carries an **op-local guard**: a zero divisor produces `0` (a finite, silent result)
//! rather than infinity. The arithmetic is generic over the number type (the pure-fn seam), so
//! the macro can instantiate it per `numbers` entry (`f32` today, `i32`/… later).
//!
//! Both carriers are generated by [`number_operator_contract!`](crate::number_operator_contract):
//! `DivF32Signal` (per-sample buffers) and `DivF32Value` (held scalars), each with the
//! multiplicative identity `1` as `b`'s unwired default.
//!
//! - input 0: `a` (`Float`) — the dividend. Unwired default `0`.
//! - input 1: `b` (`Float`) — the divisor. Unwired default `1`; a `0` divisor yields `0`.
//! - output 0: `out` — `a / b` (or `0` when `b == 0`).

/// The op's scalar math, written once (the pure-fn seam) and generic over the number type. The
/// `b == 0` check is `div`'s **op-local** guard against an `inf`/`NaN` (or integer divide panic)
/// blowing up the graph; it lives here, inherited by no other op. `Zero` supplies both the zero
/// comparison and the guarded result, so the op works for any numeric type.
#[inline]
fn div_fn<T: num_traits::Zero + core::ops::Div<Output = T>>(a: T, b: T) -> T {
    if b.is_zero() {
        T::zero()
    } else {
        a / b
    }
}

// One declaration -> DivF32Value + DivF32Signal. The multiplicative identity `1` is `b`'s
// unwired default, so wiring only `a` passes it through. Division is not commutative —
// the identity rule holds for the divisor only.
crate::number_operator_contract!(Div {
    numbers:  [f32],
    carriers: [value, signal],
    inputs:   { a: number { default 0.0 }, b: number { default 1.0 } },
    outputs:  { out },
    function: div_fn(a, b),
});

#[cfg(test)]
mod tests {
    use super::div_f32_signal::{self, DivF32Signal};
    use super::div_f32_value::{self, DivF32Value};
    use crate::operators::math_test::{signal_out, value_emits};

    /// Drive the signal form; `None` leaves the port unwired (engine materializes its default).
    fn sig(a: Option<&[f32]>, b: Option<&[f32]>, n: usize) -> Vec<f32> {
        signal_out(DivF32Signal::new(), div_f32_signal::OUT_OUT, n, |d| {
            if let Some(a) = a {
                d.drive(div_f32_signal::IN_A, a);
            }
            if let Some(b) = b {
                d.drive(div_f32_signal::IN_B, b);
            }
        })
    }

    /// Drive the value form; returns the emitted quotient(s).
    fn val(a: Option<f32>, b: Option<f32>) -> Vec<f32> {
        value_emits(DivF32Value::new(), |d| {
            if let Some(a) = a {
                d.set(div_f32_value::IN_A, a);
            }
            if let Some(b) = b {
                d.set(div_f32_value::IN_B, b);
            }
        })
    }

    #[test]
    fn divides_two_buffers() {
        let a = [10.0, 20.0, 9.0];
        let b = [2.0, 5.0, 3.0];
        assert_eq!(sig(Some(&a), Some(&b), 3), vec![5.0, 4.0, 3.0]);
    }

    #[test]
    fn unwired_b_is_unity() {
        // Multiplicative identity 1: wiring only `a` passes it through.
        let a = [5.0, 6.0, 7.0];
        assert_eq!(sig(Some(&a), None, 3), vec![5.0, 6.0, 7.0]);
    }

    #[test]
    fn zero_divisor_yields_zero_no_inf() {
        // The op-local guard keeps the graph finite: a/0 -> 0, never ±inf/NaN.
        let a = [1.0, -2.0, 3.0];
        let b = [0.0, 0.0, 0.0];
        let out = sig(Some(&a), Some(&b), 3);
        assert!(out.iter().all(|s| s.is_finite()));
        assert_eq!(out, vec![0.0, 0.0, 0.0]);
    }

    #[test]
    fn divides_held_operands() {
        assert_eq!(val(Some(12.0), Some(4.0)), vec![3.0]);
    }

    #[test]
    fn held_zero_divisor_yields_zero() {
        assert_eq!(val(Some(5.0), Some(0.0)), vec![0.0]);
    }
}
