//! `map` — dense affine remap, the Good Button workhorse.
//!
//! A pointwise `Float`→`Float` shaper: `brightness [0,1] → cutoff [800,10000]` with a response
//! curve. `in` is a materialized `Float`, the four bounds are number operands, and `curve` is a held
//! [`MapCurve`] mode. Default inputs are the identity `[0,1] → [0,1]` linear, so an unconfigured
//! `map` is a transparent pass-through (the public face of a Good Button).
//!
//! Both carriers are generated by [`number_operator_contract!`](crate::number_operator_contract):
//! `MapF32Signal` (per-sample) and `MapF32Value` (held). The four bounds follow the
//! carrier like any number operand (per-sample buffers in the signal form); `curve` is an enum mode,
//! so it is **always held** (enums have no buffer form). The affine math is the module-level
//! [`remap`] fn (the pure-fn seam), which owns the curve test.
//!
//! - input 0: `in` (`Float`) — the value to remap (per-sample).
//! - inputs 1–4: `in_min`, `in_max`, `out_min`, `out_max` (`Float`).
//! - input 5: `curve` (`Enum` [`MapCurve`] {Linear, Exponential}).
//! - output 0: `out` — the remapped value.

use crate::vocab::MapCurve;

/// Affine (optionally exponential) remap of `v` from `[in_min, in_max]` onto `[out_min, out_max]`,
/// clamped to the input range. The op's scalar math, written once (the pure-fn seam). The
/// `curve` mode lives here: exponential is used only when both output bounds are positive (it is
/// meaningless across zero), else it falls back to linear.
fn remap(v: f32, in_min: f32, in_max: f32, out_min: f32, out_max: f32, curve: MapCurve) -> f32 {
    let span = in_max - in_min;
    let t = if span.abs() < 1e-12 {
        0.0
    } else {
        ((v - in_min) / span).clamp(0.0, 1.0)
    };
    if curve == MapCurve::Exponential && out_min > 0.0 && out_max > 0.0 {
        out_min * (out_max / out_min).powf(t)
    } else {
        out_min + t * (out_max - out_min)
    }
}

// One declaration -> MapF32Value + MapF32Signal. The bounds default to the identity
// [0,1] -> [0,1]; `curve` defaults (via MapCurve::default) to Linear, so an unconfigured map is a
// pass-through. Renamed from `map` -> `map_f32_signal` (+ new `map_f32_value`) to join the family.
crate::number_operator_contract!(Map {
    numbers:  [f32],
    carriers: [value, signal],
    inputs:   {
        in:      number { default 0.0 },
        in_min:  number { default 0.0 },
        in_max:  number { default 1.0 },
        out_min: number { default 0.0 },
        out_max: number { default 1.0 },
        curve:   enum(MapCurve),
    },
    outputs:  { out },
    function: remap(in, in_min, in_max, out_min, out_max, curve),
});

#[cfg(test)]
mod tests {
    use super::map_f32_signal::{self, MapF32Signal};
    use super::map_f32_value::{self, MapF32Value};
    use crate::operators::math_test::{signal_out, value_emits};
    use crate::vocab::MapCurve;

    /// Drive the signal form: `in` is a per-sample buffer; the bounds + curve are held (set once,
    /// materialised) — exactly how the engine latches them.
    #[allow(clippy::too_many_arguments)]
    fn run_map(
        in_min: f32,
        in_max: f32,
        out_min: f32,
        out_max: f32,
        curve: MapCurve,
        values: &[f32],
    ) -> Vec<f32> {
        signal_out(
            MapF32Signal::new(),
            map_f32_signal::OUT_OUT,
            values.len(),
            |d| {
                d.set(map_f32_signal::IN_IN_MIN, in_min);
                d.set(map_f32_signal::IN_IN_MAX, in_max);
                d.set(map_f32_signal::IN_OUT_MIN, out_min);
                d.set(map_f32_signal::IN_OUT_MAX, out_max);
                d.set(map_f32_signal::IN_CURVE, curve);
                d.drive(map_f32_signal::IN_IN, values);
            },
        )
    }

    #[test]
    fn identity_passes_value_through() {
        let out = run_map(0.0, 1.0, 0.0, 1.0, MapCurve::Linear, &[0.42; 4]);
        for &s in &out {
            approx::assert_relative_eq!(s, 0.42);
        }
    }

    #[test]
    fn linear_remaps_range_and_clamps() {
        // [0,1] -> [800,10000] linear. 0.5 -> 5400; an over-range 2.0 clamps to 10000.
        let out = run_map(0.0, 1.0, 800.0, 10_000.0, MapCurve::Linear, &[0.5, 2.0]);
        approx::assert_relative_eq!(out[0], 5400.0);
        approx::assert_relative_eq!(out[1], 10_000.0);
    }

    #[test]
    fn zero_width_input_range_yields_out_min_no_nan() {
        // The bounds are live per-sample signal inputs, so a degenerate range like [0.5, 0.5] is
        // a reachable runtime state. The span guard (|in_max - in_min| < 1e-12) forces t = 0, so
        // every sample maps to out_min — never NaN/inf from the zero-span division. Input samples
        // at, below, and above the degenerate bound all behave the same (map's op-local NaN
        // guard, the same class every sibling math op pins).
        let out = run_map(0.5, 0.5, 2.0, 8.0, MapCurve::Linear, &[0.5, 0.0, 1.0]);
        for &s in &out {
            assert!(s.is_finite());
            approx::assert_relative_eq!(s, 2.0);
        }
        // Same guard under Exponential (positive bounds): out_min * (out_max/out_min)^0 = out_min.
        let out = run_map(0.5, 0.5, 2.0, 8.0, MapCurve::Exponential, &[0.0, 1.0]);
        for &s in &out {
            approx::assert_relative_eq!(s, 2.0);
        }
    }

    #[test]
    fn exponential_curve_is_geometric_midpoint() {
        // [0,1] -> [100,10000] exponential: t=0.5 -> sqrt(100*10000)=1000.
        let out = run_map(0.0, 1.0, 100.0, 10_000.0, MapCurve::Exponential, &[0.5]);
        approx::assert_relative_eq!(out[0], 1000.0, epsilon = 1e-1);
    }

    #[test]
    fn exponential_with_nonpositive_bound_falls_back_to_linear() {
        // out_min < 0: geometric interpolation is meaningless across zero -> the documented
        // linear fallback (module doc). A regression applying out_min * (out_max/out_min).powf(t)
        // here would yield NaN (negative-base powf) at t = 0.5.
        let out = run_map(0.0, 1.0, -1.0, 1.0, MapCurve::Exponential, &[0.0, 0.5, 1.0]);
        assert!(out.iter().all(|s| s.is_finite()));
        approx::assert_relative_eq!(out[0], -1.0);
        approx::assert_relative_eq!(out[1], 0.0);
        approx::assert_relative_eq!(out[2], 1.0);

        // Boundary of the strict `> 0.0` check: out_min == 0.0 also falls back to linear
        // (exponential would collapse to a constant 0 or divide by zero).
        let out = run_map(0.0, 1.0, 0.0, 10.0, MapCurve::Exponential, &[0.5]);
        approx::assert_relative_eq!(out[0], 5.0);
    }

    #[test]
    fn is_per_sample() {
        // A rising input ramp produces a rising output ramp (dense, no event gating).
        let out = run_map(
            0.0,
            1.0,
            0.0,
            10.0,
            MapCurve::Linear,
            &[0.0, 0.25, 0.5, 1.0],
        );
        approx::assert_relative_eq!(out[0], 0.0);
        approx::assert_relative_eq!(out[1], 2.5);
        approx::assert_relative_eq!(out[2], 5.0);
        approx::assert_relative_eq!(out[3], 10.0);
    }

    #[test]
    fn value_form_remaps_held_input() {
        // Held in=0.5 over identity input range onto [0,10] -> 5.0, emitted once.
        let out = value_emits(MapF32Value::new(), |d| {
            d.set(map_f32_value::IN_IN, 0.5);
            d.set(map_f32_value::IN_OUT_MAX, 10.0);
        });
        approx::assert_relative_eq!(out[0], 5.0);
    }
}
