//! Math operator family — the mapping/gesture toolkit (ADR-0017).
//!
//! "Math is what gestures are made of." A small family of arithmetic operators, the
//! arithmetic written **once** against a [`Number`] trait and the per-domain shells
//! generated from it, so the Message and Signal domains cannot drift:
//!
//! - **`add` / `mul`** — Signal-domain, two audio-rate buffers in, one out. The sanctioned
//!   way to combine two streams: **base-plus-modulation** is an explicit `add` (ADR-0017),
//!   ring-modulation / scaling an explicit `mul`. Each input carries an **unwired default
//!   scalar** equal to the op's identity (0 for `add`, 1 for `mul`), so wiring only one side
//!   passes the other through. Generated by [`signal_pointwise!`] from the `Number` core.
//! - **`map`** — Message-domain affine remap with input/output ranges and a response curve:
//!   the Good Button workhorse (`brightness [0,1] → cutoff [800,10000]`). One Message in →
//!   one Message out, 1:1 (a "fan map" buys nothing over Message fan-out — ADR-0017).
//! - **`differentiate` / `integrate`** — Message-domain calculus with **real frame-based
//!   `dt`** taken from the sample-accurate frame every Message carries, accumulated across
//!   block boundaries. `differentiate` = Δvalue / Δt_sec (a gesture's velocity);
//!   `integrate` = Σ value · Δt.
//!
//! All Message-domain ops here are **single-input** and consume *any* incoming value event
//! (first numeric arg), emitting on the `out` port — so they compose freely whether the
//! value arrives from outside (OSC to the node address) or from an upstream emit. Multi-input
//! Message arithmetic (`add`/`mul` per numeric type) waits on port-tagged Message routing;
//! combining two *streams* lives in the Signal domain today, which is where modulation
//! naturally is.

use crate::descriptor::{Curve, Descriptor, LaneRule, ParamMeta, Port};
use crate::message::Arg;
use crate::operator::{Io, Operator};

/// Signal input ordinal `a` (the pointwise ops' first operand).
pub const IN_A: usize = 0;
/// Signal input ordinal `b` (the pointwise ops' second operand).
pub const IN_B: usize = 1;
/// The single output port ordinal, shared by every op in this module.
pub const OUT_OUT: usize = 0;
/// Message-output ordinal of the `out` port on the Message-domain ops.
pub const MSG_OUT: usize = 0;

/// The numeric trait the family's arithmetic is written against **once** (ADR-0017). `f32`
/// today; integer Message variants are one `impl` + one macro line away. The `*_IDENTITY`
/// constants double as the unwired-default scalar for each pointwise op's Signal ports.
pub trait Number: Copy {
    const ADD_IDENTITY: Self;
    const MUL_IDENTITY: Self;
    fn add(self, rhs: Self) -> Self;
    fn mul(self, rhs: Self) -> Self;
}

impl Number for f32 {
    const ADD_IDENTITY: Self = 0.0;
    const MUL_IDENTITY: Self = 1.0;
    #[inline]
    fn add(self, rhs: Self) -> Self {
        self + rhs
    }
    #[inline]
    fn mul(self, rhs: Self) -> Self {
        self * rhs
    }
}

/// Generate a two-input, one-output **Signal** pointwise operator from the [`Number`] core.
/// Adding `sub` / `min` / `max` later is one more invocation — the per-sample plumbing and
/// the descriptor live here, never re-typed (ADR-0017).
macro_rules! signal_pointwise {
    ($name:ident, $type_name:literal, $doc:literal, $identity:expr, $apply:expr) => {
        #[doc = $doc]
        #[derive(Default)]
        pub struct $name;

        impl $name {
            pub fn new() -> Self {
                Self
            }
        }

        impl Operator for $name {
            fn descriptor() -> Descriptor {
                Descriptor {
                    type_name: $type_name,
                    inputs: vec![Port::signal("a"), Port::signal("b")],
                    outputs: vec![Port::signal("out")],
                    params: vec![],
                    resources: vec![],
                    lanes: LaneRule::Inherit,
                }
            }

            fn process(&mut self, io: &mut Io) {
                let n = io.frames();
                // Each input falls back to the op's identity when unwired, so wiring only one
                // side passes it through unchanged (base-plus-modulation; ADR-0017).
                let id = $identity;
                for i in 0..n {
                    let a = io.input(IN_A).map_or(id, |s| s[i]);
                    let b = io.input(IN_B).map_or(id, |s| s[i]);
                    io.output(OUT_OUT)[i] = $apply(a, b);
                }
            }

            fn spawn(&self) -> Box<dyn Operator> {
                Box::new(Self::new())
            }
        }

        $crate::register_operator!($name);
    };
}

signal_pointwise!(
    Add,
    "add",
    "Signal `add` — `out = a + b`, per sample. Base-plus-modulation (ADR-0017).",
    <f32 as Number>::ADD_IDENTITY,
    |a: f32, b: f32| Number::add(a, b)
);

signal_pointwise!(
    Mul,
    "mul",
    "Signal `mul` — `out = a * b`, per sample. Ring-mod / amplitude scaling.",
    <f32 as Number>::MUL_IDENTITY,
    |a: f32, b: f32| Number::mul(a, b)
);

// --- Message-domain affine map (the Good Button workhorse) ---

pub const P_IN_MIN: usize = 0;
pub const P_IN_MAX: usize = 1;
pub const P_OUT_MIN: usize = 2;
pub const P_OUT_MAX: usize = 3;
pub const P_CURVE: usize = 4;
pub const P_DEFAULT: usize = 5;

/// Affine (optionally exponential) remap of `v` from `[in_min, in_max]` onto
/// `[out_min, out_max]`, clamped to the input range. Exponential is used only when both
/// output bounds are positive (it is meaningless across zero), else it falls back to linear.
fn remap(v: f32, in_min: f32, in_max: f32, out_min: f32, out_max: f32, exp: bool) -> f32 {
    let span = in_max - in_min;
    let t = if span.abs() < 1e-12 {
        0.0
    } else {
        ((v - in_min) / span).clamp(0.0, 1.0)
    };
    if exp && out_min > 0.0 && out_max > 0.0 {
        out_min * (out_max / out_min).powf(t)
    } else {
        out_min + t * (out_max - out_min)
    }
}

/// `map` — Message-domain affine remap. One value Message in → one remapped value out.
///
/// - input 0: `in` (Message) — value events; the first numeric arg is remapped.
/// - output 0 (Message): `out` — the remapped value at the same frame.
/// - params: `in_min`, `in_max`, `out_min`, `out_max`, `curve` (0 = linear, 1 = exponential),
///   `default` (input-domain resting value, ADR-0018).
///
/// Default params are the identity `[0,1] → [0,1]` linear, so an unconfigured `map` is a
/// transparent pass-through (the public face of a Good Button). Single-Lane (ADR-0014):
/// emission is pre-fan-out.
///
/// **Emit-on-init (ADR-0018):** on its first block, before any message, `map` emits
/// `remap(default)` at frame 0 so a Good Button's whole downstream chain converges to the
/// resting position its control-surface widget shows — sound and UI agree at rest. The seed
/// fires once per instance and re-arms on [`spawn`](Operator::spawn).
#[derive(Default)]
pub struct Map {
    /// Whether the resting `default` has been emitted yet (emit-on-init). Reset on `spawn()`.
    seeded: bool,
}

impl Map {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Operator for Map {
    fn descriptor() -> Descriptor {
        Descriptor {
            type_name: "map",
            inputs: vec![Port::message("in")],
            outputs: vec![Port::message("out")],
            params: vec![
                ParamMeta {
                    name: "in_min",
                    min: -1_000_000.0,
                    max: 1_000_000.0,
                    default: 0.0,
                    unit: "",
                    curve: Curve::Linear,
                },
                ParamMeta {
                    name: "in_max",
                    min: -1_000_000.0,
                    max: 1_000_000.0,
                    default: 1.0,
                    unit: "",
                    curve: Curve::Linear,
                },
                ParamMeta {
                    name: "out_min",
                    min: -1_000_000.0,
                    max: 1_000_000.0,
                    default: 0.0,
                    unit: "",
                    curve: Curve::Linear,
                },
                ParamMeta {
                    name: "out_max",
                    min: -1_000_000.0,
                    max: 1_000_000.0,
                    default: 1.0,
                    unit: "",
                    curve: Curve::Linear,
                },
                ParamMeta {
                    name: "curve",
                    min: 0.0,
                    max: 1.0,
                    default: 0.0,
                    unit: "",
                    curve: Curve::Linear,
                },
                // Input-domain resting value (ADR-0018). The static default equals the default
                // `in_min`; an instrument that customizes the input range should set `default`
                // to taste so the resting position stays inside it.
                ParamMeta {
                    name: "default",
                    min: -1_000_000.0,
                    max: 1_000_000.0,
                    default: 0.0,
                    unit: "",
                    curve: Curve::Linear,
                },
            ],
            resources: vec![],
            lanes: LaneRule::Inherit,
        }
    }

    fn process(&mut self, io: &mut Io) {
        let in_min = io.param(P_IN_MIN);
        let in_max = io.param(P_IN_MAX);
        let out_min = io.param(P_OUT_MIN);
        let out_max = io.param(P_OUT_MAX);
        let exp = io.param(P_CURVE) >= 0.5;

        // Emit the resting value once, before any message, so a Good Button's chain converges
        // to the position its widget shows (ADR-0018). A real event at frame 0 lands after this
        // and wins, so live input still overrides the resting default.
        if !self.seeded {
            let out = remap(io.param(P_DEFAULT), in_min, in_max, out_min, out_max, exp);
            io.emit(MSG_OUT, "out", [Arg::Float(out)], 0);
            self.seeded = true;
        }

        // Snapshot value events (can't read events while emitting).
        let mut values: smallvec::SmallVec<[(usize, f32); 8]> = smallvec::SmallVec::new();
        for ev in io.events() {
            if let Some(v) = ev.args.first().and_then(Arg::as_f32) {
                values.push((ev.frame, v));
            }
        }
        for (frame, v) in values {
            let out = remap(v, in_min, in_max, out_min, out_max, exp);
            io.emit(MSG_OUT, "out", [Arg::Float(out)], frame);
        }
    }

    fn spawn(&self) -> Box<dyn Operator> {
        Box::new(Self::new())
    }
}

crate::register_operator!(Map);

// --- Message-domain calculus (frame-based dt) ---

/// `differentiate` — Message-domain rate of change. Emits `Δvalue / Δt_sec` per input event,
/// where `Δt_sec` comes from the sample-accurate frame each Message carries (the velocity of
/// a gesture). The first event after construction has no predecessor, so it emits nothing.
///
/// - input 0: `in` (Message) — value events.
/// - output 0 (Message): `out` — the derivative at the input frame.
#[derive(Default)]
pub struct Differentiate {
    /// (absolute frame, value) of the previous event, across block boundaries.
    last: Option<(u64, f32)>,
    /// Total samples elapsed before this block — turns a block-relative frame absolute.
    elapsed: u64,
}

impl Differentiate {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Operator for Differentiate {
    fn descriptor() -> Descriptor {
        Descriptor {
            type_name: "differentiate",
            inputs: vec![Port::message("in")],
            outputs: vec![Port::message("out")],
            params: vec![],
            resources: vec![],
            lanes: LaneRule::Inherit,
        }
    }

    fn process(&mut self, io: &mut Io) {
        let n = io.frames();
        let sr = io.sample_rate();

        let mut values: smallvec::SmallVec<[(usize, f32); 8]> = smallvec::SmallVec::new();
        for ev in io.events() {
            if let Some(v) = ev.args.first().and_then(Arg::as_f32) {
                values.push((ev.frame.min(n), v));
            }
        }
        values.sort_by_key(|(f, _)| *f);

        let mut last = self.last;
        for (frame, v) in values {
            let abs = self.elapsed + frame as u64;
            if let Some((lf, lv)) = last {
                if abs > lf && sr > 0.0 {
                    let dt = (abs - lf) as f32 / sr;
                    io.emit(MSG_OUT, "out", [Arg::Float((v - lv) / dt)], frame);
                }
            }
            last = Some((abs, v));
        }
        self.last = last;
        self.elapsed += n as u64;
    }

    fn spawn(&self) -> Box<dyn Operator> {
        Box::new(Self::new())
    }
}

crate::register_operator!(Differentiate);

/// `integrate` — Message-domain running integral. Treats the input as a piecewise-constant
/// signal held at the previous value, accumulating `Σ value · Δt_sec`, and emits the running
/// total per input event. The first event seeds the accumulator (emits the current total, 0).
///
/// - input 0: `in` (Message) — value events.
/// - output 0 (Message): `out` — the running integral at the input frame.
#[derive(Default)]
pub struct Integrate {
    acc: f32,
    last: Option<(u64, f32)>,
    elapsed: u64,
}

impl Integrate {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Operator for Integrate {
    fn descriptor() -> Descriptor {
        Descriptor {
            type_name: "integrate",
            inputs: vec![Port::message("in")],
            outputs: vec![Port::message("out")],
            params: vec![],
            resources: vec![],
            lanes: LaneRule::Inherit,
        }
    }

    fn process(&mut self, io: &mut Io) {
        let n = io.frames();
        let sr = io.sample_rate();

        let mut values: smallvec::SmallVec<[(usize, f32); 8]> = smallvec::SmallVec::new();
        for ev in io.events() {
            if let Some(v) = ev.args.first().and_then(Arg::as_f32) {
                values.push((ev.frame.min(n), v));
            }
        }
        values.sort_by_key(|(f, _)| *f);

        let mut last = self.last;
        let mut acc = self.acc;
        for (frame, v) in values {
            let abs = self.elapsed + frame as u64;
            if let Some((lf, lv)) = last {
                if abs > lf && sr > 0.0 {
                    acc += lv * ((abs - lf) as f32 / sr);
                }
            }
            io.emit(MSG_OUT, "out", [Arg::Float(acc)], frame);
            last = Some((abs, v));
        }
        self.acc = acc;
        self.last = last;
        self.elapsed += n as u64;
    }

    fn spawn(&self) -> Box<dyn Operator> {
        Box::new(Self::new())
    }
}

crate::register_operator!(Integrate);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::message::{Emit, Event, Message};

    const SR: f32 = 48_000.0;

    /// Run a Signal pointwise op over one block with the given a/b inputs; returns `out`.
    fn run_signal(
        op: &mut dyn Operator,
        a: Option<&[f32]>,
        b: Option<&[f32]>,
        n: usize,
    ) -> Vec<f32> {
        let mut out = vec![0.0f32; n];
        {
            let inputs: Vec<Option<&[f32]>> = vec![a, b];
            let outs: Vec<&mut [f32]> = vec![&mut out[..]];
            let mut io = Io::new(SR, n, inputs, outs, &[], &[]);
            op.process(&mut io);
        }
        out
    }

    /// Run a Message op over one block of value events; returns its emissions.
    fn run_msg(op: &mut dyn Operator, params: &[f32], values: &[Message]) -> Vec<Emit> {
        let evs: Vec<Event> = values
            .iter()
            .map(|m| Event {
                addr: &m.addr,
                args: &m.args,
                frame: m.frame,
            })
            .collect();
        let mut emits: Vec<Emit> = Vec::new();
        {
            let outs: Vec<&mut [f32]> = vec![];
            let inputs: Vec<Option<&[f32]>> = vec![None];
            let mut io = Io::new(SR, 256, inputs, outs, params, &evs).with_emit(&mut emits, 0);
            op.process(&mut io);
        }
        emits
    }

    fn val(addr: &str, v: f32, frame: usize) -> Message {
        Message::new(addr, [Arg::Float(v)], frame)
    }

    #[test]
    fn add_sums_two_buffers() {
        let a = [1.0, 2.0, 3.0];
        let b = [10.0, 20.0, 30.0];
        let out = run_signal(&mut Add::new(), Some(&a), Some(&b), 3);
        assert_eq!(out, vec![11.0, 22.0, 33.0]);
    }

    #[test]
    fn add_unwired_b_passes_a_through() {
        // Base-plus-modulation with the modulation unwired: identity 0 leaves the base.
        let a = [5.0, 6.0, 7.0];
        let out = run_signal(&mut Add::new(), Some(&a), None, 3);
        assert_eq!(out, vec![5.0, 6.0, 7.0]);
    }

    #[test]
    fn mul_unwired_b_is_unity() {
        let a = [5.0, 6.0, 7.0];
        let out = run_signal(&mut Mul::new(), Some(&a), None, 3);
        assert_eq!(out, vec![5.0, 6.0, 7.0]);
    }

    #[test]
    fn mul_products_two_buffers() {
        let a = [1.0, 2.0, 4.0];
        let b = [3.0, 3.0, 0.5];
        let out = run_signal(&mut Mul::new(), Some(&a), Some(&b), 3);
        assert_eq!(out, vec![3.0, 6.0, 2.0]);
    }

    #[test]
    fn map_identity_passes_value_through() {
        let emits = run_msg(
            &mut Map::new(),
            &[0.0, 1.0, 0.0, 1.0, 0.0, 0.0],
            &[val("in", 0.42, 7)],
        );
        // First block seeds the resting default (0.0) at frame 0 (ADR-0018), then the value.
        assert_eq!(emits.len(), 2);
        assert_eq!(emits[0].frame, 0);
        approx::assert_relative_eq!(emits[0].args[0].as_f32().unwrap(), 0.0);
        assert_eq!(emits[1].addr, "out");
        assert_eq!(emits[1].frame, 7);
        approx::assert_relative_eq!(emits[1].args[0].as_f32().unwrap(), 0.42);
    }

    #[test]
    fn map_linear_remaps_range_and_clamps() {
        // [0,1] -> [800,10000] linear. 0.5 -> 5400; an over-range 2.0 clamps to 10000.
        // emits[0] is the resting seed (default 0.0 -> 800).
        let params = [0.0, 1.0, 800.0, 10_000.0, 0.0, 0.0];
        let emits = run_msg(
            &mut Map::new(),
            &params,
            &[val("in", 0.5, 0), val("in", 2.0, 1)],
        );
        approx::assert_relative_eq!(emits[0].args[0].as_f32().unwrap(), 800.0);
        approx::assert_relative_eq!(emits[1].args[0].as_f32().unwrap(), 5400.0);
        approx::assert_relative_eq!(emits[2].args[0].as_f32().unwrap(), 10_000.0);
    }

    #[test]
    fn map_exponential_curve_is_geometric_midpoint() {
        // [0,1] -> [100,10000] exponential: t=0.5 -> sqrt(100*10000)=1000.
        // emits[0] is the resting seed (default 0.0, t=0 -> out_min 100).
        let params = [0.0, 1.0, 100.0, 10_000.0, 1.0, 0.0];
        let emits = run_msg(&mut Map::new(), &params, &[val("in", 0.5, 0)]);
        approx::assert_relative_eq!(emits[1].args[0].as_f32().unwrap(), 1000.0, epsilon = 1e-1);
    }

    #[test]
    fn map_consumes_events_regardless_of_address() {
        // External OSC to the node address arrives with an empty local address; chained
        // emits arrive as "out". Both must drive the map. emits[0] is the resting seed.
        let p = [0.0, 1.0, 0.0, 10.0, 0.0, 0.0];
        let from_external = run_msg(&mut Map::new(), &p, &[val("", 0.5, 0)]);
        let from_chain = run_msg(&mut Map::new(), &p, &[val("out", 0.5, 0)]);
        approx::assert_relative_eq!(from_external[1].args[0].as_f32().unwrap(), 5.0);
        approx::assert_relative_eq!(from_chain[1].args[0].as_f32().unwrap(), 5.0);
    }

    #[test]
    fn map_emits_resting_default_once_on_first_block() {
        // default=0.5 over [0,1]->[0,100]: first block emits 50 at frame 0 with no events;
        // a second block with no events emits nothing — the seed fires once per instance.
        let mut m = Map::new();
        let params = [0.0, 1.0, 0.0, 100.0, 0.0, 0.5];
        let first = run_msg(&mut m, &params, &[]);
        assert_eq!(first.len(), 1);
        assert_eq!(first[0].frame, 0);
        approx::assert_relative_eq!(first[0].args[0].as_f32().unwrap(), 50.0);
        let second = run_msg(&mut m, &params, &[]);
        assert!(second.is_empty(), "resting seed fires once per instance");
    }

    #[test]
    fn spawned_map_re_seeds_resting_default() {
        let mut m = Map::new();
        let params = [0.0, 1.0, 0.0, 100.0, 0.0, 0.5];
        let _ = run_msg(&mut m, &params, &[]);
        let mut m2 = m.spawn();
        let emits = run_msg(&mut *m2, &params, &[]);
        assert_eq!(emits.len(), 1, "spawn re-arms the resting seed");
        approx::assert_relative_eq!(emits[0].args[0].as_f32().unwrap(), 50.0);
    }

    #[test]
    fn differentiate_emits_velocity_with_frame_dt() {
        // Two events 24000 samples apart (0.5 s @ 48k); Δvalue 1.0 -> 2.0 units/sec.
        let mut d = Differentiate::new();
        let emits = run_msg(&mut d, &[], &[val("in", 0.0, 0), val("in", 1.0, 100)]);
        // 100 samples apart -> dt = 100/48000; slope = 1.0 / (100/48000) = 480.
        assert_eq!(emits.len(), 1, "first event seeds, second emits");
        approx::assert_relative_eq!(emits[0].args[0].as_f32().unwrap(), 480.0, epsilon = 1e-2);
    }

    #[test]
    fn differentiate_dt_carries_across_blocks() {
        // Event at block-1 frame 0, next at block-2 frame 0 (256 samples later).
        let mut d = Differentiate::new();
        let _ = run_msg(&mut d, &[], &[val("in", 0.0, 0)]);
        let emits = run_msg(&mut d, &[], &[val("in", 1.0, 0)]);
        approx::assert_relative_eq!(
            emits[0].args[0].as_f32().unwrap(),
            1.0 / (256.0 / SR),
            epsilon = 1e-1
        );
    }

    #[test]
    fn integrate_accumulates_value_times_dt() {
        // Hold value 2.0 from frame 0 to frame 100, then read at 100: acc = 2.0 * 100/48000.
        let mut i = Integrate::new();
        let emits = run_msg(&mut i, &[], &[val("in", 2.0, 0), val("in", 9.0, 100)]);
        approx::assert_relative_eq!(emits[0].args[0].as_f32().unwrap(), 0.0); // seed
        approx::assert_relative_eq!(
            emits[1].args[0].as_f32().unwrap(),
            2.0 * (100.0 / SR),
            epsilon = 1e-6
        );
    }

    #[test]
    fn spawned_math_ops_start_fresh() {
        let mut d = Differentiate::new();
        let _ = run_msg(&mut d, &[], &[val("in", 0.0, 0), val("in", 5.0, 50)]);
        let mut d2 = d.spawn();
        // Fresh: first event after spawn seeds (no emission), exactly like a new op.
        let emits = run_msg(&mut *d2, &[], &[val("in", 1.0, 0)]);
        assert!(emits.is_empty(), "spawned differentiate must re-seed");
    }
}
