//! `mul` — `out = a * b`, per sample (ADR-0029, ADR-0017, ADR-0033).
//!
//! The sanctioned way to **combine two streams multiplicatively**: ring-modulation, amplitude
//! scaling, and the VCA (`env.cv -> power -> mul`, audio on the other input — ADR-0027). A dense
//! `Float`→`Float` op — both operands are materialized `Float` inputs whose unwired default is the
//! multiplicative identity `1`, so wiring only one side passes it through unchanged (ADR-0028
//! materialize fills the other with ones). Its arithmetic is the generic [`mul_fn`], called once per
//! sample by the generated signal shell and once per change by the value shell (issue #83).
//!
//! Both carriers are generated by [`number_operator_contract!`](crate::number_operator_contract)
//! (ADR-0033): `MulF32Signal` and `MulF32Value`, each with the multiplicative identity `1` as its
//! operands' unwired default.
//!
//! - input 0: `a` (`Float`) — first operand. Unwired default `1`.
//! - input 1: `b` (`Float`) — second operand. Unwired default `1`.
//! - output 0: `out` — `a * b`.

/// The op's scalar math, written once (ADR-0029 pure-fn seam) and generic over the number type so
/// the macro can instantiate it per `numbers` entry (`f32` today).
#[inline]
fn mul_fn<T: core::ops::Mul<Output = T>>(a: T, b: T) -> T {
    a * b
}

// One declaration -> MulF32Value + MulF32Signal (ADR-0033). The multiplicative identity `1` is the
// operands' declared default, so wiring only one side passes it through (ADR-0029). The generated
// `defaults_are_data` test pins that `1` — a forgotten default would fail it, not silently zero.
crate::number_operator_contract!(Mul {
    numbers:  [f32],
    carriers: [value, signal],
    inputs:   { a: number { default 1.0 }, b: number { default 1.0 } },
    outputs:  { out },
    function: mul_fn(a, b),
});

#[cfg(test)]
mod tests {
    use super::mul_f32_signal::{self, MulF32Signal};
    use super::mul_f32_value::{self, MulF32Value};
    use crate::operators::math_test::{signal_out, value_emits};

    /// Drive the signal form; `None` leaves the port unwired (engine materializes its identity `1`).
    fn sig(a: Option<&[f32]>, b: Option<&[f32]>, n: usize) -> Vec<f32> {
        signal_out(MulF32Signal::new(), mul_f32_signal::OUT_OUT, n, |d| {
            if let Some(a) = a {
                d.drive(mul_f32_signal::IN_A, a);
            }
            if let Some(b) = b {
                d.drive(mul_f32_signal::IN_B, b);
            }
        })
    }

    /// Drive the value form; returns the emitted product(s).
    fn val(a: Option<f32>, b: Option<f32>) -> Vec<f32> {
        value_emits(MulF32Value::new(), |d| {
            if let Some(a) = a {
                d.set(mul_f32_value::IN_A, a);
            }
            if let Some(b) = b {
                d.set(mul_f32_value::IN_B, b);
            }
        })
    }

    #[test]
    fn products_two_buffers() {
        let a = [1.0, 2.0, 4.0];
        let b = [3.0, 3.0, 0.5];
        assert_eq!(sig(Some(&a), Some(&b), 3), vec![3.0, 6.0, 2.0]);
    }

    #[test]
    fn unwired_b_is_unity() {
        // Multiplicative identity 1: wiring only `a` passes it through.
        let a = [5.0, 6.0, 7.0];
        assert_eq!(sig(Some(&a), None, 3), vec![5.0, 6.0, 7.0]);
    }

    #[test]
    fn products_held_operands() {
        assert_eq!(val(Some(4.0), Some(2.5)), vec![10.0]);
    }

    #[test]
    fn unwired_held_b_is_unity() {
        assert_eq!(val(Some(7.0), None), vec![7.0]);
    }
}
