//! PowerF32Signal — a unipolar curve shaper, `out = x^exponent`, per sample (ADR-0027, ADR-0033).
//!
//! The first member of the curve-op family (issue #40): named for the precise math curve it
//! applies (a *power* curve), not a generic "curve" knob — future shapes get their own ops
//! (`logarithmic`, …). It exists to turn the envelope's **linear** CV into a perceptually
//! natural **volume** contour: the ear hears loudness roughly logarithmically, so a linear
//! amplitude decay sounds abrupt. Raising the linear `[0, 1]` contour to a power (≈2) tracks an
//! exponential-style decay closely while still hitting exactly 0 at release and 1 at the peak —
//! no silence floor to fudge. Patch it between an `envelope` and a `mul`: `env.cv -> power.x`,
//! `power.out -> mul`, audio -> the other `mul` input.
//!
//! Both carriers are generated by [`number_operator_contract!`](crate::number_operator_contract)
//! (ADR-0033): `PowerF32Signal` (per-sample buffers) and `PowerF32Value` (held scalars). Both `x`
//! and `exponent` are number operands following the carrier — in the signal form `exponent` is now
//! read **per sample** (a uniform buffer operand) rather than once block-rate; functionally identical
//! for a held control (block-slicing re-runs on change), and it drops the bespoke block-rate read.
//! The op is `f32`-only: its scalar [`shape`] uses `f32`-specific `max`/`powf` for the unipolar NaN
//! guard, so it lists `numbers: [f32]`.
//!
//! - input 0: `x` (`Float`) — the value to shape; treated as unipolar (negatives clamp to 0 so a
//!   fractional exponent never yields NaN). Unwired default 0.
//! - input 1: `exponent` (`Float`) — the power. Default 2 (a musical amplitude curve); 1 is a
//!   pass-through.
//! - output 0: `out` — `x^exponent`.

/// The op's scalar math, written once (ADR-0029 pure-fn seam): a unipolar power curve. The
/// `max(0.0)` is `power`'s **op-local** NaN guard (a fractional exponent over a negative base is
/// NaN); it lives here, inherited by no other op. `f32`-specific, hence `power` is `f32`-only.
#[inline]
fn shape(x: f32, exponent: f32) -> f32 {
    x.max(0.0).powf(exponent)
}

// One declaration -> PowerF32Value + PowerF32Signal (ADR-0033). `x` defaults to 0 over the full
// range; `exponent` defaults to 2 over [0, 8]. Both follow the carrier (per-sample in the signal
// form). Port names x/exponent and the type_names are preserved -> no instrument/schema churn beyond
// `exponent`'s form (Value -> Signal-with-meta), which a held source still materialises (ADR-0030).
crate::number_operator_contract!(Power {
    numbers:  [f32],
    carriers: [value, signal],
    inputs:   { x: number { default 0.0 }, exponent: number { 0.0..=8.0, default 2.0 } },
    outputs:  { out },
    function: shape(x, exponent),
});

#[cfg(test)]
mod tests {
    use super::power_f32_signal::{self, PowerF32Signal};
    use super::power_f32_value::{self, PowerF32Value};
    use crate::operators::math_test::{signal_out, value_emits};
    use approx::assert_abs_diff_eq;

    /// Drive the signal form; `x` is a per-sample buffer (`None` leaves it unwired -> default 0),
    /// `exponent` is set as a held knob (materialised to a constant buffer).
    fn sig(x: Option<&[f32]>, exponent: f32, n: usize) -> Vec<f32> {
        signal_out(PowerF32Signal::new(), power_f32_signal::OUT_OUT, n, |d| {
            d.set(power_f32_signal::IN_EXPONENT, exponent);
            if let Some(x) = x {
                d.drive(power_f32_signal::IN_X, x);
            }
        })
    }

    /// Drive the value form; returns the emitted shaped value(s).
    fn val(x: f32, exponent: f32) -> Vec<f32> {
        value_emits(PowerF32Value::new(), |d| {
            d.set(power_f32_value::IN_X, x);
            d.set(power_f32_value::IN_EXPONENT, exponent);
        })
    }

    #[test]
    fn squares_the_input_by_default() {
        let x = [0.0, 0.25, 0.5, 1.0];
        let out = sig(Some(&x), 2.0, x.len());
        assert_abs_diff_eq!(out[0], 0.0, epsilon = 1e-6);
        assert_abs_diff_eq!(out[1], 0.0625, epsilon = 1e-6);
        assert_abs_diff_eq!(out[2], 0.25, epsilon = 1e-6);
        assert_abs_diff_eq!(out[3], 1.0, epsilon = 1e-6);
    }

    #[test]
    fn fixes_the_endpoints() {
        // Any exponent maps 0 -> 0 and 1 -> 1, so the curve only bends the interior — a release
        // still reaches true silence and a peak still reaches unity.
        for &k in &[0.5, 1.0, 2.0, 3.5, 8.0] {
            let out = sig(Some(&[0.0, 1.0]), k, 2);
            assert_abs_diff_eq!(out[0], 0.0, epsilon = 1e-6);
            assert_abs_diff_eq!(out[1], 1.0, epsilon = 1e-6);
        }
    }

    #[test]
    fn exponent_one_is_passthrough() {
        let x = [0.1, 0.3, 0.7, 0.9];
        let out = sig(Some(&x), 1.0, x.len());
        for (o, i) in out.iter().zip(&x) {
            assert_abs_diff_eq!(o, i, epsilon = 1e-6);
        }
    }

    #[test]
    fn negative_input_clamps_to_zero_no_nan() {
        // A fractional exponent over a negative base would be NaN; the unipolar clamp prevents it.
        let out = sig(Some(&[-1.0, -0.5, 0.0]), 0.5, 3);
        assert!(out.iter().all(|s| s.is_finite()));
        assert_abs_diff_eq!(out[0], 0.0, epsilon = 1e-6);
        assert_abs_diff_eq!(out[1], 0.0, epsilon = 1e-6);
    }

    #[test]
    fn unwired_input_is_silent() {
        let out = sig(None, 2.0, 4);
        assert!(out.iter().all(|&s| s == 0.0));
    }

    #[test]
    fn value_form_squares_by_default() {
        assert_abs_diff_eq!(val(0.5, 2.0)[0], 0.25, epsilon = 1e-6);
    }

    #[test]
    fn value_form_clamps_negative_no_nan() {
        let out = val(-0.5, 0.5);
        assert!(out[0].is_finite());
        assert_abs_diff_eq!(out[0], 0.0, epsilon = 1e-6);
    }
}
