//! `sub` — `out = a - b`, per sample.
//!
//! The sanctioned way to **subtract one stream from another**: difference, detune, bias removal. A
//! dense `Float`→`Float` op — `b`'s unwired default is the subtractive identity `0`, so wiring only
//! `a` passes it through unchanged (an unwired Value materializes to its default at the Signal
//! input). One of the math family's pointwise members; its arithmetic is the generic [`sub_fn`],
//! called once per sample by the signal shell and once per change by the value shell (issue #83).
//!
//! Both carriers are generated by [`number_operator_contract!`](crate::number_operator_contract):
//! `SubF32Signal` (per-sample buffers) and `SubF32Value` (held scalars), each with the
//! subtractive identity `0` as `b`'s unwired default.
//!
//! - input 0: `a` (`Float`) — the minuend. Unwired default `0`.
//! - input 1: `b` (`Float`) — the subtrahend. Unwired default `0`.
//! - output 0: `out` — `a - b`.

use crate::operators::pointwise::PointwiseNum;

/// The op's scalar math, written once (the pure-fn seam) and generic over the number type so the
/// macro can instantiate it per `variants:` entry.
///
/// [`PointwiseNum`] rather than `core::ops::Sub`: the difference must be total at every
/// instantiated type, and `i32`'s `-` panics on overflow in a debug build (a render-thread panic)
/// where `f32`'s yields `-inf`.
#[inline]
fn sub_fn<T: PointwiseNum>(a: T, b: T) -> T {
    a.sub(b)
}

// One declaration -> SubF32Value + SubF32Signal. The subtractive identity `0` is `b`'s
// unwired default, so wiring only `a` passes it through. Note the family's identity rule
// holds for the second operand only — subtraction is not commutative, unlike add/mul.
crate::number_operator_contract!(Sub {
    variants: [f32 value, f32 signal, i32 value],
    inputs:   { a: number { default 0.0 }, b: number { default 0.0 } },
    outputs:  { out },
    function: sub_fn(a, b),
});

#[cfg(test)]
mod tests {
    use super::sub_f32_signal::{self, SubF32Signal};
    use super::sub_f32_value::{self, SubF32Value};
    use crate::operators::math_test::{signal_out, value_emits};

    /// Drive the signal form; `None` leaves the port unwired (engine materializes its default `0`).
    fn sig(a: Option<&[f32]>, b: Option<&[f32]>, n: usize) -> Vec<f32> {
        signal_out(SubF32Signal::new(), sub_f32_signal::OUT_OUT, n, |d| {
            if let Some(a) = a {
                d.drive(sub_f32_signal::IN_A, a);
            }
            if let Some(b) = b {
                d.drive(sub_f32_signal::IN_B, b);
            }
        })
    }

    /// Drive the value form; returns the emitted difference(s).
    fn val(a: Option<f32>, b: Option<f32>) -> Vec<f32> {
        value_emits(SubF32Value::new(), |d| {
            if let Some(a) = a {
                d.set(sub_f32_value::IN_A, a);
            }
            if let Some(b) = b {
                d.set(sub_f32_value::IN_B, b);
            }
        })
    }

    #[test]
    fn subtracts_two_buffers() {
        let a = [10.0, 20.0, 30.0];
        let b = [1.0, 2.0, 3.0];
        assert_eq!(sig(Some(&a), Some(&b), 3), vec![9.0, 18.0, 27.0]);
    }

    #[test]
    fn unwired_b_passes_a_through() {
        // Subtractive identity 0: wiring only `a` leaves it unchanged.
        let a = [5.0, 6.0, 7.0];
        assert_eq!(sig(Some(&a), None, 3), vec![5.0, 6.0, 7.0]);
    }

    #[test]
    fn unwired_a_negates_b() {
        // `a` defaults to 0, so wiring only `b` yields `0 - b`.
        let b = [2.0, -3.0, 4.0];
        assert_eq!(sig(None, Some(&b), 3), vec![-2.0, 3.0, -4.0]);
    }

    #[test]
    fn subtracts_held_operands() {
        assert_eq!(val(Some(7.0), Some(4.0)), vec![3.0]);
    }

    #[test]
    fn unwired_held_b_passes_a_through() {
        assert_eq!(val(Some(5.0), None), vec![5.0]);
    }
}
