//! `unpack_op!` — generate an `unpack_<type>` operator that destructures a product vocab type into
//! its held fields.
//!
//! A product vocab type (`Note { pitch, velocity }`) can be *destructured on the wire* by an
//! operator that reads the whole value as an **Event** stream on `in` and emits each field as a
//! **held `Value`** (the Event→Value latch). This is pure boilerplate apart
//! from the type and its field→wire-form list, so this macro takes that one declaration and emits
//! the whole operator: the contract (via the shared [`render_contract`](crate::render_contract), so
//! it is byte-identical in shape to a hand-written `operator_contract!` op), an empty-but-for-latch
//! struct, the `Operator` impl whose `process` is the Voicer's frame-sorted latch,
//! `register_operator!`, and the re-export.
//!
//! ```ignore
//! unpack_op!(Note {
//!     pitch: pitch,       // a held `Pitch` leaf output
//!     velocity: f32,      // a held `f32` output
//! });
//! // -> unpack::UnpackNote (type_name "unpack_note"): in: Note event -> pitch, velocity held Values
//! ```
//!
//! **Why the field list, not just the type** (the naive `unpack_op!(vocab::Note)` can't work): a
//! function-like proc-macro sees only the tokens `Note`, so it cannot introspect the struct's
//! fields — the field names and their wire forms must be named here. Listing them keeps the
//! unpackable surface *explicit and auditable in one greppable file*, exactly the property we want.
//!
//! The **input** is currently hardcoded to a `note` Event (`Note` is the only event-carried product
//! vocab type today). Unpacking a *different* event-carried product type is not just a census line:
//! `to_spec` fixes the input port to `note` and the state snapshots `Note` payloads, so that type's
//! event input form must be taught here first.

use proc_macro2::{Span, TokenStream};
use quote::quote;
use reuben_contract::{naming, F32Meta, OperatorSpec, PortSpec, PortTy, NUMBER_MAX, NUMBER_MIN};
use syn::ext::IdentExt;
use syn::parse::{Parse, ParseStream};
use syn::{braced, Error, Ident, Token};

use crate::model::build;
use crate::render_contract;

/// The proc-macro body, over `proc_macro2` so it is unit-testable without a proc-macro context.
pub(crate) fn expand(input: TokenStream) -> TokenStream {
    let parsed = match syn::parse2::<UnpackInput>(input) {
        Ok(p) => p,
        Err(e) => return e.to_compile_error(),
    };
    parsed.render()
}

/// One declared output field: its name and the held wire form it takes.
struct Field {
    /// The field name, verbatim — the output port name. Un-raw'd so a keyword field
    /// yields a legal const/accessor.
    name: Ident,
    /// The field's port type, driving both the contract port and the emitted handle form.
    ty: PortTy,
}

struct UnpackInput {
    /// The product vocab type destructured, e.g. `Note` — the operator is `Unpack<Type>`, its state
    /// holds a whole `<Type>`, and it reads/accesses that type's fields.
    vocab: Ident,
    fields: Vec<Field>,
}

impl UnpackInput {
    fn render(&self) -> TokenStream {
        let struct_name = format!("Unpack{}", self.vocab);
        let struct_ident = Ident::new(&struct_name, self.vocab.span());
        let type_name = naming::type_name_from_struct(&struct_name);
        let mod_ident = Ident::new(&type_name, self.vocab.span());

        let spec = self.to_spec(&type_name);
        if let Err(err) = reuben_contract::validate(&spec) {
            return Error::new(self.vocab.span(), err.message).to_compile_error();
        }
        let model = build(&spec);
        let contract = render_contract(&struct_ident, &model);
        let process = self.process_body(&model);

        let vocab = &self.vocab;
        quote! {
            pub mod #mod_ident {
                use super::*;
                use ::reuben_core::descriptor::Descriptor;
                use ::reuben_core::operator::{Io, Operator};

                #contract

                /// An `unpack_<type>` operator, generated by `unpack_op!`: reads the whole input value
                /// as an event stream on `in` and holds each field as a `Value` output.
                pub struct #struct_ident {
                    /// The latched value, held across blocks (ZOH). Its fields seed the frame-0
                    /// baseline every block; a `Default` before the first event.
                    held: #vocab,
                    /// Reusable per-block event snapshot `(frame, value)`, so `process` never
                    /// allocates once warm — the Voicer's discipline (`voicer.rs`).
                    events: ::std::vec::Vec<(usize, #vocab)>,
                }

                impl #struct_ident {
                    pub fn new() -> Self {
                        Self {
                            held: <#vocab as ::core::default::Default>::default(),
                            events: ::std::vec::Vec::with_capacity(16),
                        }
                    }
                }

                // Uncalled, and deliberately kept — see the same note in `number_op.rs`: every
                // operator in `reuben-core` carries `Default` because
                // `clippy::new_without_default` demands it, and clippy cannot see into a foreign
                // macro's expansion to demand it here.
                impl ::core::default::Default for #struct_ident {
                    fn default() -> Self {
                        Self::new()
                    }
                }

                impl Operator for #struct_ident {
                    fn descriptor() -> Descriptor {
                        Self::contract()
                    }

                    fn process(&mut self, io: &mut Io) {
                        #process
                    }

                    fn spawn(&self) -> ::std::boxed::Box<dyn Operator> {
                        ::std::boxed::Box::new(Self::new())
                    }
                }

                crate::register_operator!(#struct_ident);
            }
            pub use #mod_ident::#struct_ident;
        }
    }

    /// The [`OperatorSpec`]: a `note` Event input `in`, one held-Value output per field. Reuses the
    /// shared validator + builder so the contract is identical to a hand-written `operator_contract!`.
    fn to_spec(&self, type_name: &str) -> OperatorSpec {
        // The input event form is hardcoded to `note` — `Note` is the only event-carried product
        // vocab type today. A different `self.vocab` would need this derived from its event form
        // (and the `Vec<(usize, #vocab)>` state matched), so the macro is Note-input-only for now.
        let inputs = vec![PortSpec {
            name: "in".to_string(),
            ty: PortTy::Note,
        }];
        let outputs = self
            .fields
            .iter()
            .map(|f| PortSpec {
                name: f.name.unraw().to_string(),
                ty: f.ty.clone(),
            })
            .collect();
        OperatorSpec {
            type_name: type_name.to_string(),
            inputs,
            outputs,
            constants: Vec::new(),
            resources: Vec::new(),
        }
    }

    /// The `process` body — the Voicer's frame-sorted latch: snapshot the `Note`
    /// event stream (can't read it while an output write borrows `io`, so snapshot first), sort by
    /// frame, then for each field emit a frame-0 baseline of the held value followed by one change
    /// per event at its frame (`MsgWriter` dedups, so steady state stays sparse; last-write-wins at
    /// a frame gives last-processed-wins). The held state advances to the last event for the next
    /// block's ZOH baseline.
    fn process_body(&self, model: &crate::model::ContractModel) -> TokenStream {
        // `IN_IN` is the sole input; the output handles are the field ports in declaration order.
        let per_field = self.fields.iter().zip(&model.outputs).map(|(f, port)| {
            let out_const = Ident::new(&port.const_name, Span::call_site());
            let field = raw(&f.name);
            quote! {
                {
                    let mut w = io.write(#out_const);
                    w.set(0, self.held.#field);
                    for &(frame, ev) in &self.events {
                        w.set(frame, ev.#field);
                    }
                }
            }
        });
        quote! {
            let n = io.frames();
            // Snapshot this (sub)block's note events, sorted by frame (last-processed-wins at a frame).
            self.events.clear();
            for s in io.read(IN_IN) {
                self.events.push((s.frame.min(n), s.payload));
            }
            self.events.sort_by_key(|e| e.0);
            #(#per_field)*
            // Advance the held state so the next block's frame-0 baseline holds the last value (ZOH).
            if let Some(&(_, last)) = self.events.last() {
                self.held = last;
            }
        }
    }
}

/// A raw identifier for a field-derived name, so a keyword field (`in`) yields a legal accessor
/// (`self.held.r#in`). Raw form of a normal name refers to the same identifier.
fn raw(name: &Ident) -> Ident {
    Ident::new_raw(&name.unraw().to_string(), name.span())
}

// --- Parsing the macro grammar ---

impl Parse for UnpackInput {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let vocab: Ident = input.parse()?;
        let body;
        braced!(body in input);
        let mut fields = Vec::new();
        while !body.is_empty() {
            // `parse_any` so a field may be named with a keyword (e.g. a hypothetical `in` field).
            let name = Ident::parse_any(&body)?;
            body.parse::<Token![:]>()?;
            let kw = Ident::parse_any(&body)?;
            let ty = match kw.to_string().as_str() {
                // A held `Pitch` leaf — the field rides its own named `Arg`.
                "pitch" => PortTy::Pitch,
                // A held `f32` Value — the type-wide range so an unwired downstream materializes a
                // sane default (mirrors `number_operator_contract!`'s value output).
                "f32" => PortTy::F32(F32Meta {
                    min: NUMBER_MIN,
                    max: NUMBER_MAX,
                    default: 0.0,
                    unit: String::new(),
                    curve: reuben_contract::Curve::Linear,
                }),
                other => {
                    return Err(Error::new(
                        kw.span(),
                        format!("unpack field form must be `pitch` or `f32`, got `{other}`"),
                    ))
                }
            };
            fields.push(Field { name, ty });
            if body.peek(Token![,]) {
                body.parse::<Token![,]>()?;
            }
        }
        if fields.is_empty() {
            return Err(Error::new(
                vocab.span(),
                "unpack_op! needs at least one output field",
            ));
        }
        Ok(UnpackInput { vocab, fields })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn render(src: &str) -> String {
        let ts: TokenStream = src.parse().expect("token stream");
        expand(ts).to_string()
    }

    // `unpack_op!(Note { pitch, velocity })` expands to the `unpack_note` module + struct, the
    // `note` event input, the two held-field outputs (a `Pitch` leaf + an `f32`), self-registration,
    // and the re-export — the same module skeleton `number_operator_contract!` emits.
    #[test]
    fn unpack_note_emits_the_operator_module() {
        let out = render(r#"Note { pitch: pitch, velocity: f32 }"#);
        assert!(out.contains("pub mod unpack_note"), "{out}");
        assert!(out.contains("pub struct UnpackNote"), "{out}");
        assert!(out.contains("type_name : \"unpack_note\""), "{out}");
        assert!(out.contains("pub use unpack_note :: UnpackNote"), "{out}");
        assert!(out.contains("register_operator ! (UnpackNote)"), "{out}");
    }

    // The input is a `Note` event on `in`; each field is a held Value output — `pitch` a `Pitch`
    // leaf, `velocity` an `f32` — with the field name verbatim as the port.
    #[test]
    fn ports_are_the_note_event_in_and_the_held_fields() {
        let out = render(r#"Note { pitch: pitch, velocity: f32 }"#);
        // Input: a `note` event handle on `in`.
        assert!(
            out.contains("Event < :: reuben_core :: vocab :: pitch :: Note >"),
            "{out}"
        );
        assert!(out.contains("Port :: note (\"in\")"), "{out}");
        // Outputs: a held `Pitch` leaf and a held `f32`, named verbatim.
        assert!(
            out.contains("Held < :: reuben_core :: vocab :: pitch :: Pitch >"),
            "{out}"
        );
        assert!(out.contains("Port :: pitch (\"pitch\")"), "{out}");
        assert!(out.contains("Held < f32 >"), "{out}");
        assert!(out.contains("Port :: f32 (\"velocity\""), "{out}");
    }

    // The `process` is the Voicer's frame-sorted latch: snapshot the event stream, sort by frame,
    // baseline-then-per-event `set` on each field's writer.
    #[test]
    fn process_is_a_frame_sorted_latch() {
        let out = render(r#"Note { pitch: pitch, velocity: f32 }"#);
        assert!(out.contains("io . read (IN_IN)"), "{out}");
        assert!(out.contains("sort_by_key"), "{out}");
        assert!(out.contains("io . write (OUT_PITCH)"), "{out}");
        assert!(out.contains("io . write (OUT_VELOCITY)"), "{out}");
        // Field accessors are raw idents (so a keyword-named field stays legal), like
        // `number_operator_contract!`'s raw operand locals.
        assert!(out.contains("self . held . r#pitch"), "{out}");
        assert!(out.contains("self . held . r#velocity"), "{out}");
    }

    // An unknown field form is a spanned error, not a silent miscompile.
    #[test]
    fn unknown_field_form_errors() {
        let out = render(r#"Note { pitch: harmony }"#);
        assert!(out.contains("compile_error"), "{out}");
        assert!(out.contains("pitch` or `f32"), "{out}");
    }

    // A census entry with no output fields is a spanned error, not an operator with no ports.
    #[test]
    fn no_output_fields_errors() {
        let out = render(r#"Note { }"#);
        assert!(out.contains("compile_error"), "{out}");
        assert!(out.contains("at least one output field"), "{out}");
    }
}
