//! The intent vocabulary — the curated word→move table (ADR-0058).
//!
//! One structured source (`docs/agents/vocabulary.json`) maps musical/mood words to ordered
//! parameter **moves** `{operator type, input, direction, magnitude, condition}` plus antonym
//! pointers. The table is instrument-blind and registry-keyed: rows name operator types and
//! input names only, never an instrument or a pipe — the join to a concrete document happens
//! in context at patch time (ADR-0058 §2). The prompt-facing artifact is a compact **rendered
//! view** (`docs/agents/vocabulary.md`), generated by [`Vocabulary::render`] via
//! `cargo run -p reuben-core --example gen_vocabulary` and staleness-checked by tests — the
//! `gen_schema` posture: one source, generated artifact, CI-checked (ADR-0058 §6).
//!
//! Freshness is split (ADR-0058 §5): **referential** truth is mechanical — [`Vocabulary::sweep`]
//! asserts every move's operator type + input name exist in the live [`Registry`], so an
//! operator rename breaks the build, not the agent; **musical** truth (does "warmer" still do
//! the right thing?) belongs to synthetic-session evals, which no mechanical check can own.
//!
//! No relation to [`crate::vocab`], the shared module of concrete `Arg` value types — this is
//! the *agent-facing descriptor* vocabulary, a docs artifact swept against the registry.

use std::collections::HashSet;

use serde::Deserialize;

use crate::registry::Registry;

/// The whole curated source: edge-conduct preamble, word rows, direction-only fallback block
/// (ADR-0058 §3; the preamble placement is ADR-0059 §2). Parsed from
/// `docs/agents/vocabulary.json` by [`Vocabulary::parse`], which also enforces the structural
/// rules serde cannot (non-empty moves, resolvable antonym pointers, no duplicate rows).
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Vocabulary {
    /// Curator-facing note carried in the source file (what this is, how to regenerate).
    /// Never rendered.
    #[serde(default)]
    pub about: String,
    /// Edge-conduct lines rendered ahead of the table (ADR-0059 §2): how to act on ambiguous
    /// or unsatisfiable asks. Content is human-locked curation (R6); this module owns shape only.
    pub preamble: Vec<String>,
    /// The table rows, in curated order. Rendering groups them by [`Section`], preserving
    /// source order within a section.
    pub words: Vec<WordEntry>,
    /// The direction-only fallback block (ADR-0058 §3): grounds words outside the table, plus
    /// the tie-breaker rule. Lines of prose — deliberately not moves, so there is nothing here
    /// for the registry sweep to pin.
    pub fallback: Vec<String>,
}

/// One table row: a word, its ordered moves, and antonym pointers into the same table.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WordEntry {
    pub word: String,
    pub section: Section,
    /// Ordered moves — applied in sequence, first is the word's primary reading.
    pub moves: Vec<Move>,
    /// Words this one is the opposite of. Each must name another row's word (any section);
    /// [`Vocabulary::parse`] rejects a dangling pointer.
    #[serde(default)]
    pub antonyms: Vec<String>,
}

/// The three day-one sections (ADR-0058 §3). Growth is eval-gated: a new section is a
/// deliberate code + curation change, never a free-form string.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Section {
    Timbral,
    Rhythmic,
    Tonal,
}

impl Section {
    /// Fixed rendering order.
    const ALL: [Section; 3] = [Section::Timbral, Section::Rhythmic, Section::Tonal];

    /// The rendered-view heading.
    fn heading(self) -> &'static str {
        match self {
            Section::Timbral => "Timbral",
            Section::Rhythmic => "Rhythmic",
            Section::Tonal => "Tonal",
        }
    }
}

/// One parameter move. `op` + `input` are the registry-owned, mechanically swept part
/// (ADR-0058 §5); `direction`/`magnitude`/`condition` are prose for the model.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Move {
    /// Operator type name ([`crate::descriptor::Descriptor::type_name`]).
    pub op: String,
    /// An input or plan-time constant port on that operator — the whole input surface, matching
    /// [`crate::introspect`]'s view.
    pub input: String,
    /// Which way to push it: `down`, `up`, `set …` — free prose, required.
    pub direction: String,
    /// How far, when it matters (`slightly`, `one octave`). Optional.
    pub magnitude: Option<String>,
    /// When this move applies — the cross-section disambiguation seat for overloaded words
    /// (ADR-0058 §3). Optional.
    pub condition: Option<String>,
}

impl Vocabulary {
    /// Parse + structurally validate the curated source. Beyond serde's shape check
    /// (`deny_unknown_fields` everywhere — a typo in a curation file must fail, not vanish),
    /// this enforces what the format means: every block non-empty, every row has moves, no
    /// duplicate `(word, section)` row (the same word *may* recur across sections — that is
    /// the overloaded-word form), and every antonym pointer resolves to a row in the table.
    pub fn parse(json: &str) -> Result<Vocabulary, String> {
        let v: Vocabulary =
            serde_json::from_str(json).map_err(|e| format!("vocabulary source: {e}"))?;

        let non_empty = |lines: &[String], block: &str| -> Result<(), String> {
            if lines.is_empty() {
                return Err(format!("vocabulary source: `{block}` block is empty"));
            }
            for l in lines {
                if l.trim().is_empty() {
                    return Err(format!(
                        "vocabulary source: `{block}` block has a blank line"
                    ));
                }
            }
            Ok(())
        };
        non_empty(&v.preamble, "preamble")?;
        non_empty(&v.fallback, "fallback")?;
        if v.words.is_empty() {
            return Err("vocabulary source: `words` is empty".to_string());
        }

        let known: HashSet<&str> = v.words.iter().map(|w| w.word.as_str()).collect();
        let mut rows: HashSet<(&str, Section)> = HashSet::new();
        for entry in &v.words {
            let word = entry.word.as_str();
            if word.trim().is_empty() {
                return Err("vocabulary source: a row has an empty `word`".to_string());
            }
            if !rows.insert((word, entry.section)) {
                return Err(format!(
                    "vocabulary source: duplicate row for '{word}' in the same section"
                ));
            }
            if entry.moves.is_empty() {
                return Err(format!("vocabulary source: '{word}' has no moves"));
            }
            for m in &entry.moves {
                for (field, value) in [
                    ("op", &m.op),
                    ("input", &m.input),
                    ("direction", &m.direction),
                ] {
                    if value.trim().is_empty() {
                        return Err(format!(
                            "vocabulary source: '{word}' has a move with an empty `{field}`"
                        ));
                    }
                }
                for (field, value) in [("magnitude", &m.magnitude), ("condition", &m.condition)] {
                    if value.as_deref().is_some_and(|s| s.trim().is_empty()) {
                        return Err(format!(
                            "vocabulary source: '{word}' has a move with a blank `{field}` — omit the field instead"
                        ));
                    }
                }
            }
            for a in &entry.antonyms {
                if a == word {
                    return Err(format!(
                        "vocabulary source: '{word}' lists itself as an antonym"
                    ));
                }
                if !known.contains(a.as_str()) {
                    return Err(format!(
                        "vocabulary source: '{word}' points at antonym '{a}', which is not a word in the table"
                    ));
                }
            }
        }
        Ok(v)
    }

    /// The registry-staleness sweep (ADR-0058 §5): every move's `op` must be a registered
    /// operator type and its `input` one of that operator's inputs **or plan-time constants**
    /// (the whole input surface, as [`crate::introspect`] presents it). Returns one message
    /// per stale reference; empty means fresh. The CI test asserts empty, so an operator or
    /// port rename breaks the build, not the agent.
    pub fn sweep(&self, registry: &Registry) -> Vec<String> {
        let mut errs = Vec::new();
        for entry in &self.words {
            for m in &entry.moves {
                match registry.get(&m.op) {
                    None => errs.push(format!(
                        "word '{}': operator type '{}' is not in the registry",
                        entry.word, m.op
                    )),
                    Some(reg) => {
                        let d = &reg.descriptor;
                        let known = d
                            .inputs
                            .iter()
                            .chain(d.constants.iter())
                            .any(|p| p.name == m.input);
                        if !known {
                            errs.push(format!(
                                "word '{}': operator '{}' has no input or constant named '{}'",
                                entry.word, m.op, m.input
                            ));
                        }
                    }
                }
            }
        }
        errs
    }

    /// Render the compact prompt-facing view (deterministic: fixed section order, source order
    /// within a section). One line per word:
    ///
    /// ```text
    /// - **warmer** — filter.cutoff down (slightly); saturator.drive up [if it still sounds thin]. ↔ brighter
    /// ```
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# Intent vocabulary — word → move\n\n");
        out.push_str(
            "<!-- GENERATED from docs/agents/vocabulary.json by \
             `cargo run -p reuben-core --example gen_vocabulary` — edit the source, not this file. -->\n",
        );
        for line in &self.preamble {
            out.push('\n');
            out.push_str(line);
            out.push('\n');
        }
        for section in Section::ALL {
            let rows: Vec<&WordEntry> =
                self.words.iter().filter(|w| w.section == section).collect();
            if rows.is_empty() {
                continue;
            }
            out.push_str(&format!("\n## {}\n\n", section.heading()));
            for row in rows {
                let moves: Vec<String> = row.moves.iter().map(render_move).collect();
                out.push_str(&format!("- **{}** — {}.", row.word, moves.join("; ")));
                if !row.antonyms.is_empty() {
                    out.push_str(&format!(" ↔ {}", row.antonyms.join(", ")));
                }
                out.push('\n');
            }
        }
        out.push_str("\n## Fallback — direction-only\n\n");
        for line in &self.fallback {
            out.push_str(&format!("- {line}\n"));
        }
        out
    }
}

/// One move in the rendered grammar: `op.input direction` + ` (magnitude)` + ` [if condition]`.
fn render_move(m: &Move) -> String {
    let mut s = format!("{}.{} {}", m.op, m.input, m.direction);
    if let Some(mag) = &m.magnitude {
        s.push_str(&format!(" ({mag})"));
    }
    if let Some(cond) = &m.condition {
        s.push_str(&format!(" [if {cond}]"));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal valid source exercising every render branch: magnitude, condition, antonyms,
    /// multiple moves, all three sections.
    const GOOD: &str = r#"{
        "preamble": ["Act on the most likely reading."],
        "words": [
            { "word": "warmer", "section": "timbral",
              "moves": [
                { "op": "filter", "input": "cutoff", "direction": "down", "magnitude": "slightly" },
                { "op": "saturator", "input": "drive", "direction": "up", "condition": "it still sounds thin" }
              ],
              "antonyms": ["brighter"] },
            { "word": "brighter", "section": "timbral",
              "moves": [ { "op": "filter", "input": "cutoff", "direction": "up" } ],
              "antonyms": ["warmer"] },
            { "word": "busier", "section": "rhythmic",
              "moves": [ { "op": "clock", "input": "division", "direction": "up" } ] },
            { "word": "sadder", "section": "tonal",
              "moves": [ { "op": "harmony", "input": "s2", "direction": "down" } ] }
        ],
        "fallback": ["Unknown word: one conservative move, then let the user react."]
    }"#;

    #[test]
    fn parses_and_renders_the_compact_grammar() {
        let v = Vocabulary::parse(GOOD).expect("valid source");
        let expected = "\
# Intent vocabulary — word → move

<!-- GENERATED from docs/agents/vocabulary.json by `cargo run -p reuben-core --example gen_vocabulary` — edit the source, not this file. -->

Act on the most likely reading.

## Timbral

- **warmer** — filter.cutoff down (slightly); saturator.drive up [if it still sounds thin]. ↔ brighter
- **brighter** — filter.cutoff up. ↔ warmer

## Rhythmic

- **busier** — clock.division up.

## Tonal

- **sadder** — harmony.s2 down.

## Fallback — direction-only

- Unknown word: one conservative move, then let the user react.
";
        assert_eq!(v.render(), expected);
    }

    #[test]
    fn sweep_accepts_live_inputs_and_constants() {
        // `filter.cutoff` / `clock.division` / `harmony.s2` are runtime inputs; swap one row to
        // the voicer's plan-time `voices` constant to pin that constants count as the input
        // surface (matching introspect's inputs-plus-constants view).
        let json = GOOD.replace(
            r#"{ "op": "clock", "input": "division", "direction": "up" }"#,
            r#"{ "op": "voicer", "input": "voices", "direction": "up" }"#,
        );
        let v = Vocabulary::parse(&json).expect("valid source");
        let errs = v.sweep(&Registry::builtin());
        assert!(errs.is_empty(), "unexpected stale rows: {errs:?}");
    }

    #[test]
    fn sweep_flags_a_departed_operator_type() {
        let json = GOOD.replace(r#""op": "clock""#, r#""op": "flanger""#);
        let v = Vocabulary::parse(&json).expect("shape is still valid");
        let errs = v.sweep(&Registry::builtin());
        assert_eq!(
            errs,
            vec!["word 'busier': operator type 'flanger' is not in the registry".to_string()]
        );
    }

    #[test]
    fn sweep_flags_a_departed_input_name() {
        let json = GOOD.replace(r#""input": "division""#, r#""input": "swing""#);
        let v = Vocabulary::parse(&json).expect("shape is still valid");
        let errs = v.sweep(&Registry::builtin());
        assert_eq!(
            errs,
            vec![
                "word 'busier': operator 'clock' has no input or constant named 'swing'"
                    .to_string()
            ]
        );
    }

    #[test]
    fn rejects_a_dangling_antonym() {
        let json = GOOD.replace(r#""antonyms": ["brighter"]"#, r#""antonyms": ["shinier"]"#);
        let err = Vocabulary::parse(&json).expect_err("dangling antonym must fail");
        assert!(err.contains("antonym 'shinier'"), "got: {err}");
    }

    #[test]
    fn rejects_a_row_with_no_moves() {
        let json = GOOD.replace(
            r#"[ { "op": "harmony", "input": "s2", "direction": "down" } ]"#,
            "[]",
        );
        let err = Vocabulary::parse(&json).expect_err("empty moves must fail");
        assert!(err.contains("'sadder' has no moves"), "got: {err}");
    }

    #[test]
    fn rejects_a_duplicate_row_but_allows_cross_section_overload() {
        // Same word twice in one section: a curation accident.
        let dup = GOOD.replace(
            r#""word": "busier", "section": "rhythmic""#,
            r#""word": "warmer", "section": "timbral""#,
        );
        let err = Vocabulary::parse(&dup).expect_err("duplicate (word, section) must fail");
        assert!(err.contains("duplicate row for 'warmer'"), "got: {err}");

        // Same word in two sections: the overloaded-word form (ADR-0058 §3, e.g. *darker*).
        let overloaded = GOOD.replace(
            r#""word": "busier", "section": "rhythmic""#,
            r#""word": "warmer", "section": "rhythmic""#,
        );
        Vocabulary::parse(&overloaded).expect("cross-section overload is legal");
    }

    #[test]
    fn rejects_an_unknown_section_or_field() {
        let bad_section = GOOD.replace(r#""section": "tonal""#, r#""section": "spatial""#);
        Vocabulary::parse(&bad_section).expect_err("unknown section must fail");

        let bad_field = GOOD.replace(
            r#""direction": "down" }"#,
            r#""direction": "down", "weight": 2 }"#,
        );
        Vocabulary::parse(&bad_field).expect_err("unknown field must fail");
    }
}
