//! The intent vocabulary — the curated word→move table. One structured source
//! (`docs/agents/vocabulary.json`) parses into this module's types via [`Vocabulary::parse`]; the
//! prompt-facing artifact is a compact rendered view (`docs/agents/vocabulary.md`), generated by
//! [`Vocabulary::render`] via `cargo run -p reuben-core --example gen_vocabulary` and checked
//! against the live [`Registry`] by [`Vocabulary::sweep`] — for staleness, and for whether each
//! move's direction and magnitude make sense on the port they resolve to.
//!
//! The rows are a **machine contract**, not prose for the model to interpret:
//! [`set_instrument_inputs_by_intent`](crate::edit::set_instrument_inputs_by_intent) reads
//! [`Vocabulary::builtin`] and applies them.
//!
//! No relation to [`crate::vocab`], the shared module of concrete `Arg` value types — this is
//! the *agent-facing descriptor* vocabulary, a docs artifact swept against the registry.
//!
//! see rules: agent-mcp

use std::collections::HashSet;
use std::fmt;

use serde::de::{self, Deserializer};
use serde::Deserialize;

use crate::descriptor::{EnumMeta, F32Meta, I32Meta, Port, PortType};
use crate::registry::Registry;

/// The committed source, compiled in. The table is a build-time artifact swept by CI, so the verb
/// that applies it reads the very rows the sweep proved fresh rather than a copy a consumer shipped.
const SOURCE: &str = include_str!("../../../docs/agents/vocabulary.json");

/// The whole curated source: edge-conduct preamble, word rows, direction-only fallback block
/// Parsed from
/// `docs/agents/vocabulary.json` by [`Vocabulary::parse`], which also enforces the structural
/// rules serde cannot (non-empty moves, resolvable antonym pointers, no duplicate rows).
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Vocabulary {
    /// Curator-facing note carried in the source file (what this is, how to regenerate).
    /// Never rendered.
    #[serde(default)]
    pub about: String,
    /// Edge-conduct lines rendered ahead of the table: how to act on ambiguous
    /// or unsatisfiable asks. Content is human-locked curation (R6); this module owns shape only.
    pub preamble: Vec<String>,
    /// The table rows, in curated order. Rendering groups them by [`Section`], preserving
    /// source order within a section.
    pub words: Vec<WordEntry>,
    /// The direction-only fallback block: grounds words outside the table, plus
    /// the tie-breaker rule. Lines of prose — deliberately not moves, so there is nothing here
    /// for the registry sweep to pin.
    pub fallback: Vec<String>,
}

/// One table row: a word, its ordered moves, and antonym pointers into the same table.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WordEntry {
    pub word: String,
    pub section: Section,
    /// Ordered moves — applied in sequence, first is the word's primary reading.
    pub moves: Vec<Move>,
    /// Words this one is the opposite of. Each must name another row's word (any section);
    /// [`Vocabulary::parse`] rejects a dangling pointer.
    #[serde(default)]
    pub antonyms: Vec<String>,
}

/// The three day-one sections. Growth is eval-gated: a new section is a
/// deliberate code + curation change, never a free-form string.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Section {
    Timbral,
    Rhythmic,
    Tonal,
}

impl Section {
    /// Fixed rendering order.
    const ALL: [Section; 3] = [Section::Timbral, Section::Rhythmic, Section::Tonal];

    /// The word the source spells this section with, and the word a caller narrowing an
    /// overloaded intent word passes.
    pub fn name(self) -> &'static str {
        match self {
            Section::Timbral => "timbral",
            Section::Rhythmic => "rhythmic",
            Section::Tonal => "tonal",
        }
    }

    /// Parse a caller's section word; `None` for anything that is not a section.
    pub fn parse(word: &str) -> Option<Section> {
        Section::ALL.into_iter().find(|s| s.name() == word)
    }

    /// The rendered-view heading.
    fn heading(self) -> &'static str {
        match self {
            Section::Timbral => "Timbral",
            Section::Rhythmic => "Rhythmic",
            Section::Tonal => "Tonal",
        }
    }
}

/// One parameter move — a **machine contract**, not prose: `op` + `input` name the port,
/// `direction` + `magnitude` say what to do to it, and only `description` is for the reader.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Move {
    /// Operator type name ([`crate::descriptor::Descriptor::type_name`]).
    pub op: String,
    /// An input or plan-time constant port on that operator — the whole input surface, matching
    /// [`crate::introspect`]'s view.
    pub input: String,
    /// Which way to push it.
    pub direction: Direction,
    /// How far, when the default step is not what the row means. Optional.
    pub magnitude: Option<Magnitude>,
    /// Free prose about this move — a hedge, a substitution rationale, the interval a `set`
    /// spells. Rendered into the view and echoed after the move is applied; **never parsed**.
    /// Optional.
    pub description: Option<String>,
}

/// Which way a move pushes its port: a relative shove either way, or an assignment. `set` is not a
/// special case of `up` — a ninth of the table assigns a named interval or policy, and an
/// assignment has no size.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Direction {
    Up,
    Down,
    Set,
}

impl Direction {
    /// The word the rendered view uses.
    fn word(self) -> &'static str {
        match self {
            Direction::Up => "up",
            Direction::Down => "down",
            Direction::Set => "set",
        }
    }
}

/// How far a move goes. Absent means the default step for the port's curve class; every other form
/// is explicit. `by`/`ratio` are the per-row escape hatches, so a row that means something the step
/// rule does not can say so without the rule growing a per-port exception.
#[derive(Debug, Clone, PartialEq)]
pub enum Magnitude {
    /// `"slightly"` — the small step for the port's curve class.
    Slightly,
    /// `{ "steps": N }` — a whole number of steps, integer ports only.
    Steps(i64),
    /// `{ "absolute": N }` — the number a `set` assigns.
    Absolute(f64),
    /// `{ "symbol": "…" }` — the enum variant a `set` assigns.
    Symbol(String),
    /// `{ "by": N }` — an additive override of the step rule.
    By(f64),
    /// `{ "ratio": R }` — a multiplicative override of the step rule.
    Ratio(f64),
}

impl Magnitude {
    /// The value a `set` assigns, rendered — `None` for the relative forms.
    fn set_target(&self) -> Option<String> {
        match self {
            Magnitude::Absolute(n) => Some(n.to_string()),
            Magnitude::Symbol(s) => Some(s.clone()),
            _ => None,
        }
    }
}

impl fmt::Display for Magnitude {
    /// The parenthetical the rendered view carries after a direction.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Magnitude::Slightly => f.write_str("slightly"),
            Magnitude::Steps(n) => write!(f, "by {n}"),
            Magnitude::Absolute(n) => write!(f, "{n}"),
            Magnitude::Symbol(s) => f.write_str(s),
            Magnitude::By(n) => write!(f, "by {n}"),
            Magnitude::Ratio(r) => write!(f, "×{r}"),
        }
    }
}

/// The object forms, for the error text: named once so the message and the match cannot drift.
const MAGNITUDE_FORMS: &str = "steps, absolute, symbol, by, ratio";

impl<'de> Deserialize<'de> for Magnitude {
    /// Two source spellings, one flat enum: the bare word `"slightly"`, or a single-key object
    /// naming the amount.
    ///
    /// A visitor rather than `#[serde(untagged)]`, and the difference is the whole point: untagged
    /// collapses every object mistake — an unknown key, an empty object, two keys, a value of the
    /// wrong type — into one "data did not match any variant". Each of those is a distinct curation
    /// mistake and says so here.
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Magnitude, D::Error> {
        struct Form;

        impl<'de> de::Visitor<'de> for Form {
            type Value = Magnitude;

            fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(
                    f,
                    "\"slightly\", or an object naming one of: {MAGNITUDE_FORMS}"
                )
            }

            fn visit_str<E: de::Error>(self, word: &str) -> Result<Magnitude, E> {
                match word {
                    "slightly" => Ok(Magnitude::Slightly),
                    other => Err(E::custom(format!(
                        "magnitude {other:?} is not a word this table knows — the only word form \
                         is \"slightly\"; every other amount is an object naming one of: \
                         {MAGNITUDE_FORMS}"
                    ))),
                }
            }

            fn visit_map<A: de::MapAccess<'de>>(self, mut map: A) -> Result<Magnitude, A::Error> {
                let Some(form) = map.next_key::<String>()? else {
                    return Err(de::Error::custom(format!(
                        "magnitude is an empty object — name one of: {MAGNITUDE_FORMS}"
                    )));
                };
                // Each `next_value` carries serde's own type error, so a `{"steps": 1.5}` says
                // which key was being read and what it wanted there.
                let magnitude = match form.as_str() {
                    "steps" => Magnitude::Steps(map.next_value()?),
                    "absolute" => Magnitude::Absolute(map.next_value()?),
                    "symbol" => Magnitude::Symbol(map.next_value()?),
                    "by" => Magnitude::By(map.next_value()?),
                    "ratio" => Magnitude::Ratio(map.next_value()?),
                    other => {
                        return Err(de::Error::custom(format!(
                            "magnitude has no `{other}` form — name one of: {MAGNITUDE_FORMS}"
                        )))
                    }
                };
                if let Some(extra) = map.next_key::<String>()? {
                    return Err(de::Error::custom(format!(
                        "magnitude names both `{form}` and `{extra}` — a magnitude is exactly one \
                         of: {MAGNITUDE_FORMS}"
                    )));
                }
                Ok(magnitude)
            }
        }

        d.deserialize_any(Form)
    }
}

/// The arithmetic class an intent move sees a port as. The axis the step rule keys on — a curve
/// class, not a range — and the axis the sweep's coherence guard checks a magnitude against.
#[derive(Debug, Clone, Copy)]
pub enum PortClass<'a> {
    /// A swept scalar, carrying the range and curve a relative step is computed from.
    Scalar(&'a F32Meta),
    /// A bounded count. One is the smallest musical unit on a count, so `slightly` and the
    /// default step are the same move.
    Int(&'a I32Meta),
    /// A closed set of named choices: assignable, never pushed in a direction.
    Enum(&'a EnumMeta),
    /// Nothing an intent move can move — a bare audio buffer, a `Note` stream, an unbounded
    /// integer atom.
    Unmovable,
}

impl PortClass<'_> {
    /// Classify one port. A scalar's meta rides on the port rather than in its type, so the
    /// numeric arm reads `meta` for both the held and the buffer-carrying form.
    pub fn of(port: &Port) -> PortClass<'_> {
        match &port.ty {
            PortType::I32 { meta: Some(m) } => PortClass::Int(m),
            PortType::Vocab {
                enum_meta: Some(e), ..
            } => PortClass::Enum(e),
            _ => match &port.meta {
                Some(m) => PortClass::Scalar(m),
                None => PortClass::Unmovable,
            },
        }
    }
}

/// Check one move against the port it resolved to: does this direction take this magnitude, and
/// does this port class have one to take? Returns one message per incoherence, `at`-prefixed for
/// the sweep's report.
fn coherence(at: &str, m: &Move, port: &Port) -> Vec<String> {
    let class = PortClass::of(port);
    let where_ = format!("`{}.{}`", m.op, m.input);
    let mut errs = Vec::new();
    if let PortClass::Unmovable = class {
        errs.push(format!(
            "{at}{where_} carries no value an intent move can move (no range, no variants)"
        ));
        return errs;
    }
    match (m.direction, &m.magnitude) {
        (Direction::Set, None) => errs.push(format!(
            "{at}{where_} is a `set` with no magnitude — a `set` needs an `absolute` or a `symbol`"
        )),
        (Direction::Set, Some(Magnitude::Absolute(v))) => match class {
            PortClass::Scalar(meta) => {
                if *v < f64::from(meta.min) || *v > f64::from(meta.max) {
                    errs.push(format!(
                        "{at}{where_} is set to {v}, outside its declared range [{}..{}]",
                        meta.min, meta.max
                    ));
                }
            }
            PortClass::Int(meta) => {
                if v.fract() != 0.0 {
                    errs.push(format!("{at}{where_} is an integer port set to {v}"));
                } else if *v < f64::from(meta.min) || *v > f64::from(meta.max) {
                    errs.push(format!(
                        "{at}{where_} is set to {v}, outside its declared range [{}..{}]",
                        meta.min, meta.max
                    ));
                }
            }
            PortClass::Enum(e) => errs.push(format!(
                "{at}{where_} is an enum set to the number {v} — use a `symbol`, one of {:?}",
                e.variants
            )),
            PortClass::Unmovable => unreachable!("returned above"),
        },
        (Direction::Set, Some(Magnitude::Symbol(s))) => match class {
            PortClass::Enum(e) => {
                if !e.variants.contains(&s.as_str()) {
                    errs.push(format!(
                        "{at}{where_} is set to the symbol {s:?}, which is not one of {:?}",
                        e.variants
                    ));
                }
            }
            _ => errs.push(format!(
                "{at}{where_} is a numeric port set to the symbol {s:?} — use an `absolute`"
            )),
        },
        (Direction::Set, Some(other)) => errs.push(format!(
            "{at}{where_} is a `set` with magnitude ({other}) — a `set` takes an `absolute` or a \
             `symbol`, never a relative amount"
        )),
        (_, Some(Magnitude::Absolute(_) | Magnitude::Symbol(_))) => errs.push(format!(
            "{at}{where_} pushes {} and also names a value to set — a relative move takes neither \
             an `absolute` nor a `symbol`",
            m.direction.word()
        )),
        (_, magnitude) => {
            if let PortClass::Enum(_) = class {
                errs.push(format!(
                    "{at}{where_} is an enum pushed {} — a closed set has no direction, so use \
                     `set` with a `symbol`",
                    m.direction.word()
                ));
            }
            match (magnitude, class) {
                (Some(Magnitude::Steps(n)), PortClass::Int(_)) if *n <= 0 => errs.push(format!(
                    "{at}{where_} moves by {n} steps — `steps` is how far, and the direction says \
                     which way"
                )),
                (Some(Magnitude::Steps(_)), PortClass::Scalar(_)) => errs.push(format!(
                    "{at}{where_} is a swept scalar moved in `steps` — steps count an integer \
                     port; a scalar takes `by` or `ratio`"
                )),
                (Some(Magnitude::By(_) | Magnitude::Ratio(_)), PortClass::Int(_)) => {
                    errs.push(format!(
                        "{at}{where_} is an integer port moved by a scalar amount — use `steps`"
                    ))
                }
                // The escape hatches' own degenerate values. `by 0` and `ratio 1` move nothing, and
                // a non-positive ratio is worse than nothing: `down` divides by it, so `ratio 0`
                // is a non-finite value heading for a document that has no spelling for one.
                (Some(Magnitude::Ratio(r)), _) if !(r.is_finite() && *r > 0.0 && *r != 1.0) => errs
                    .push(format!(
                        "{at}{where_} moves by a ratio of {r} — a ratio is a finite multiplier \
                         above zero and not 1, and the direction says which way it applies"
                    )),
                (Some(Magnitude::By(by)), _) if !(by.is_finite() && *by != 0.0) => {
                    errs.push(format!(
                        "{at}{where_} moves by {by} — `by` is a finite non-zero amount, and the \
                         direction says which way it applies"
                    ))
                }
                _ => {}
            }
        }
    }
    errs
}

impl Vocabulary {
    /// The committed table, compiled in — what
    /// [`set_instrument_inputs_by_intent`](crate::edit::set_instrument_inputs_by_intent) applies.
    /// Panics on a source the sweep would have rejected, which is a broken build rather than a
    /// runtime condition: the same bytes are parsed by a CI test on every commit.
    pub fn builtin() -> Vocabulary {
        Vocabulary::parse(SOURCE).expect("the compiled-in vocabulary source parses")
    }

    /// The row for `word`, narrowed by `section` when the caller named one.
    ///
    /// `Err` carries what to do about it: an unknown word, or an ambiguous one the caller must
    /// choose a section for. Returns the row **and** the other rows the word has, so a caller
    /// that took the most likely reading can name the alternative it passed over — the table's own
    /// preamble, mechanized.
    pub fn row(
        &self,
        word: &str,
        section: Option<Section>,
    ) -> Result<(&WordEntry, Vec<Section>), String> {
        let hits: Vec<&WordEntry> = self.words.iter().filter(|w| w.word == word).collect();
        let (chosen, rest) = match (hits.as_slice(), section) {
            ([], _) => {
                return Err(format!(
                    "`{word}` is not in the intent vocabulary — read the vocabulary guide for the \
                     words it does carry, or make the move yourself with `set_instrument_input`"
                ))
            }
            (rows, Some(want)) => match rows.iter().find(|w| w.section == want) {
                Some(row) => (*row, Vec::new()),
                None => {
                    let have: Vec<String> = rows
                        .iter()
                        .map(|w| w.section.heading().to_lowercase())
                        .collect();
                    return Err(format!(
                        "`{word}` has no {} row — the table carries it as {}",
                        want.heading().to_lowercase(),
                        have.join(", ")
                    ));
                }
            },
            // Overloaded and unnarrowed: the first row in curated order is the most likely
            // reading, and the caller is told what it did not get.
            ([first, others @ ..], None) => (*first, others.iter().map(|w| w.section).collect()),
        };
        Ok((chosen, rest))
    }

    /// Parse + structurally validate the curated source. Beyond serde's shape check
    /// (`deny_unknown_fields` everywhere — a typo in a curation file must fail, not vanish),
    /// this enforces what the format means: every block non-empty, every row has moves, no
    /// duplicate `(word, section)` row (the same word *may* recur across sections — that is
    /// the overloaded-word form), and every antonym pointer resolves to a row in the table.
    pub fn parse(json: &str) -> Result<Vocabulary, String> {
        let v: Vocabulary =
            serde_json::from_str(json).map_err(|e| format!("vocabulary source: {e}"))?;

        let non_empty = |lines: &[String], block: &str| -> Result<(), String> {
            if lines.is_empty() {
                return Err(format!("vocabulary source: `{block}` block is empty"));
            }
            for l in lines {
                if l.trim().is_empty() {
                    return Err(format!(
                        "vocabulary source: `{block}` block has a blank line"
                    ));
                }
            }
            Ok(())
        };
        non_empty(&v.preamble, "preamble")?;
        non_empty(&v.fallback, "fallback")?;
        if v.words.is_empty() {
            return Err("vocabulary source: `words` is empty".to_string());
        }

        let known: HashSet<&str> = v.words.iter().map(|w| w.word.as_str()).collect();
        let mut rows: HashSet<(&str, Section)> = HashSet::new();
        for entry in &v.words {
            let word = entry.word.as_str();
            if word.trim().is_empty() {
                return Err("vocabulary source: a row has an empty `word`".to_string());
            }
            if !rows.insert((word, entry.section)) {
                return Err(format!(
                    "vocabulary source: duplicate row for '{word}' in the same section"
                ));
            }
            if entry.moves.is_empty() {
                return Err(format!("vocabulary source: '{word}' has no moves"));
            }
            for m in &entry.moves {
                for (field, value) in [("op", &m.op), ("input", &m.input)] {
                    if value.trim().is_empty() {
                        return Err(format!(
                            "vocabulary source: '{word}' has a move with an empty `{field}`"
                        ));
                    }
                }
                if m.description
                    .as_deref()
                    .is_some_and(|s| s.trim().is_empty())
                {
                    return Err(format!(
                        "vocabulary source: '{word}' has a move with a blank `description` — omit the field instead"
                    ));
                }
            }
            for a in &entry.antonyms {
                if a == word {
                    return Err(format!(
                        "vocabulary source: '{word}' lists itself as an antonym"
                    ));
                }
                if !known.contains(a.as_str()) {
                    return Err(format!(
                        "vocabulary source: '{word}' points at antonym '{a}', which is not a word in the table"
                    ));
                }
            }
        }
        Ok(v)
    }

    /// The registry-staleness sweep: every move's `op` must be a registered
    /// operator type and its `input` one of that operator's inputs **or plan-time constants**
    /// (the whole input surface, as [`crate::introspect`] presents it). Returns one message
    /// per stale reference; empty means fresh. The CI test asserts empty, so an operator or
    /// port rename breaks the build, not the agent.
    ///
    /// It also carries the **coherence** guard, because this is the one place that has resolved
    /// each move's port and therefore knows its type: a `set` needs something to set, `up`/`down`
    /// have nowhere to put one, and a step count or a variant name only mean anything on the port
    /// class that has them.
    pub fn sweep(&self, registry: &Registry) -> Vec<String> {
        let mut errs = Vec::new();
        for entry in &self.words {
            for m in &entry.moves {
                let at = format!("word '{}': ", entry.word);
                let Some(reg) = registry.get(&m.op) else {
                    errs.push(format!(
                        "{at}operator type '{}' is not in the registry",
                        m.op
                    ));
                    continue;
                };
                let d = &reg.descriptor;
                let Some(port) = d
                    .inputs
                    .iter()
                    .chain(d.constants.iter())
                    .find(|p| p.name == m.input)
                else {
                    errs.push(format!(
                        "{at}operator '{}' has no input or constant named '{}'",
                        m.op, m.input
                    ));
                    continue;
                };
                errs.extend(coherence(&at, m, port));
            }
        }
        errs
    }

    /// Render the compact prompt-facing view (deterministic: fixed section order, source order
    /// within a section). One line per word:
    ///
    /// ```text
    /// - **warmer** — filter.cutoff down (slightly); saturator.drive up [if it still sounds thin]. ↔ brighter
    /// ```
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# Intent vocabulary — word → move\n\n");
        // The header names its guard rather than ending in the doctrine's `— edit the source, not
        // this file.`, which is `scripts/ii_verify.py`'s identity test for an artifact generated
        // from templates it cannot see and so obliged to carry a `sha256=` of itself. This file's
        // source is in this repo and the named test re-renders from it, which is strictly stronger
        // than a digest; claiming the doctrine grammar would ask for a second, weaker mechanism.
        out.push_str(
            "<!-- GENERATED from docs/agents/vocabulary.json by \
             `cargo run -p reuben-core --example gen_vocabulary`; guarded by \
             `committed_rendered_view_is_in_sync`, which re-renders from that source. Do not \
             hand-edit. -->\n",
        );
        for line in &self.preamble {
            out.push('\n');
            out.push_str(line);
            out.push('\n');
        }
        for section in Section::ALL {
            let rows: Vec<&WordEntry> =
                self.words.iter().filter(|w| w.section == section).collect();
            if rows.is_empty() {
                continue;
            }
            out.push_str(&format!("\n## {}\n\n", section.heading()));
            for row in rows {
                let moves: Vec<String> = row.moves.iter().map(render_move).collect();
                out.push_str(&format!("- **{}** — {}.", row.word, moves.join("; ")));
                if !row.antonyms.is_empty() {
                    out.push_str(&format!(" ↔ {}", row.antonyms.join(", ")));
                }
                out.push('\n');
            }
        }
        out.push_str("\n## Fallback — direction-only\n\n");
        for line in &self.fallback {
            out.push_str(&format!("- {line}\n"));
        }
        out
    }
}

/// One move in the rendered grammar: `op.input direction` — a `set` absorbing its target into the
/// word (`set Chord`) and a relative move carrying its size in parentheses — then ` [description]`.
fn render_move(m: &Move) -> String {
    let mut s = format!("{}.{} {}", m.op, m.input, m.direction.word());
    match (&m.magnitude, m.direction) {
        (Some(mag), Direction::Set) => match mag.set_target() {
            Some(target) => s.push_str(&format!(" {target}")),
            None => s.push_str(&format!(" ({mag})")),
        },
        (Some(mag), _) => s.push_str(&format!(" ({mag})")),
        (None, _) => {}
    }
    if let Some(description) = &m.description {
        s.push_str(&format!(" [{description}]"));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal valid source exercising every render branch: each magnitude form, a description,
    /// antonyms, multiple moves, all three sections.
    const GOOD: &str = r#"{
        "preamble": ["Act on the most likely reading."],
        "words": [
            { "word": "warmer", "section": "timbral",
              "moves": [
                { "op": "filter", "input": "cutoff", "direction": "down", "magnitude": "slightly" },
                { "op": "saturator", "input": "drive", "direction": "up", "description": "it still sounds thin" }
              ],
              "antonyms": ["brighter"] },
            { "word": "brighter", "section": "timbral",
              "moves": [ { "op": "filter", "input": "cutoff", "direction": "up" } ],
              "antonyms": ["warmer"] },
            { "word": "busier", "section": "rhythmic",
              "moves": [ { "op": "clock", "input": "division", "direction": "up", "magnitude": { "steps": 2 } } ] },
            { "word": "sadder", "section": "tonal",
              "moves": [ { "op": "harmony", "input": "s2", "direction": "set", "magnitude": { "absolute": 3 } } ] }
        ],
        "fallback": ["Unknown word: one conservative move, then let the user react."]
    }"#;

    #[test]
    fn parses_and_renders_the_compact_grammar() {
        let v = Vocabulary::parse(GOOD).expect("valid source");
        let expected = "\
# Intent vocabulary — word → move

<!-- GENERATED from docs/agents/vocabulary.json by `cargo run -p reuben-core --example gen_vocabulary`; guarded by `committed_rendered_view_is_in_sync`, which re-renders from that source. Do not hand-edit. -->

Act on the most likely reading.

## Timbral

- **warmer** — filter.cutoff down (slightly); saturator.drive up [it still sounds thin]. ↔ brighter
- **brighter** — filter.cutoff up. ↔ warmer

## Rhythmic

- **busier** — clock.division up (by 2).

## Tonal

- **sadder** — harmony.s2 set 3.

## Fallback — direction-only

- Unknown word: one conservative move, then let the user react.
";
        assert_eq!(v.render(), expected);
    }

    #[test]
    fn every_magnitude_form_parses_to_its_variant() {
        let form = |json: &str| -> Magnitude {
            let source = GOOD.replace(
                r#""magnitude": { "steps": 2 }"#,
                &format!(r#""magnitude": {json}"#),
            );
            let v = Vocabulary::parse(&source).expect("valid source");
            v.words
                .iter()
                .find(|w| w.word == "busier")
                .expect("the row is there")
                .moves[0]
                .magnitude
                .clone()
                .expect("the move carries one")
        };
        assert_eq!(form(r#""slightly""#), Magnitude::Slightly);
        assert_eq!(form(r#"{ "steps": 3 }"#), Magnitude::Steps(3));
        assert_eq!(form(r#"{ "absolute": 4.5 }"#), Magnitude::Absolute(4.5));
        assert_eq!(
            form(r#"{ "symbol": "Chord" }"#),
            Magnitude::Symbol("Chord".into())
        );
        assert_eq!(form(r#"{ "by": 2 }"#), Magnitude::By(2.0));
        assert_eq!(form(r#"{ "ratio": 1.5 }"#), Magnitude::Ratio(1.5));
    }

    /// Each object mistake is a different curation mistake and says which one it is — the whole
    /// reason this is a visitor rather than `#[serde(untagged)]`, which collapses all four into one
    /// "data did not match any variant".
    #[test]
    fn rejects_a_magnitude_form_the_table_does_not_know() {
        let rejected = |bad: &str| -> String {
            let source = GOOD.replace(
                r#""magnitude": { "steps": 2 }"#,
                &format!(r#""magnitude": {bad}"#),
            );
            Vocabulary::parse(&source).expect_err("an unknown magnitude form must fail")
        };
        for (bad, expected) in [
            (r#""a lot""#, "\"a lot\""),
            (r#"{ "octaves": 1 }"#, "no `octaves` form"),
            (r#"{}"#, "empty object"),
            (r#"{ "steps": 1, "by": 2 }"#, "both `steps` and `by`"),
            (r#"{ "steps": 1.5 }"#, "1.5"),
            ("12", "integer"),
        ] {
            let err = rejected(bad);
            assert!(err.contains(expected), "{bad} -> {err}");
        }
    }

    /// The escape hatches carry their own degenerate values: `by 0` and `ratio 1` move nothing, and
    /// `ratio 0` is worse — `down` divides by it, so it is a non-finite value heading for a document
    /// that has no way to spell one.
    #[test]
    fn sweep_flags_a_degenerate_escape_hatch() {
        let registry = Registry::builtin();
        for (bad, expected) in [
            (r#"{ "ratio": 0 }"#, "ratio of 0"),
            (r#"{ "ratio": -2 }"#, "ratio of -2"),
            (r#"{ "ratio": 1 }"#, "ratio of 1"),
            (r#"{ "by": 0 }"#, "moves by 0"),
        ] {
            let json = GOOD.replace(
                r#"{ "op": "filter", "input": "cutoff", "direction": "up" }"#,
                &format!(
                    r#"{{ "op": "filter", "input": "cutoff", "direction": "up", "magnitude": {bad} }}"#
                ),
            );
            let errs = Vocabulary::parse(&json)
                .expect("shape is still valid")
                .sweep(&registry);
            assert_eq!(errs.len(), 1, "{bad} -> {errs:?}");
            assert!(errs[0].contains(expected), "{bad} -> {}", errs[0]);
        }
    }

    /// The overloaded-word form the report has to survive: the first row in curated order is taken
    /// and the rest come back so the caller can name what it passed over.
    #[test]
    fn row_takes_the_first_reading_and_reports_the_rest() {
        let overloaded = GOOD.replace(
            r#""word": "sadder", "section": "tonal""#,
            r#""word": "warmer", "section": "tonal""#,
        );
        let v = Vocabulary::parse(&overloaded).expect("cross-section overload is legal");

        let (row, rest) = v
            .row("warmer", None)
            .expect("an overloaded word still resolves");
        assert_eq!(row.section, Section::Timbral);
        assert_eq!(rest, vec![Section::Tonal]);

        let (narrowed, rest) = v
            .row("warmer", Some(Section::Tonal))
            .expect("the named section wins");
        assert_eq!(narrowed.section, Section::Tonal);
        assert!(rest.is_empty(), "nothing was passed over: {rest:?}");

        let unknown = v.row("shinier", None).expect_err("not a word in the table");
        assert!(unknown.contains("shinier"), "{unknown}");
        let wrong_section = v
            .row("brighter", Some(Section::Tonal))
            .expect_err("brighter is timbral only");
        assert!(wrong_section.contains("timbral"), "{wrong_section}");
    }

    /// The coherence guard rides the sweep, because the sweep is what resolved the port and so is
    /// the only place that knows its class.
    #[test]
    fn sweep_flags_an_incoherent_direction_and_magnitude() {
        let registry = Registry::builtin();
        let flagged = |from: &str, to: &str| -> String {
            let json = GOOD.replace(from, to);
            let mut errs = Vocabulary::parse(&json)
                .expect("shape is still valid")
                .sweep(&registry);
            assert_eq!(errs.len(), 1, "expected exactly one finding: {errs:?}");
            errs.remove(0)
        };

        // A `set` with nothing to set, and a shove that names one anyway.
        let bare_set = flagged(
            r#""direction": "set", "magnitude": { "absolute": 3 }"#,
            r#""direction": "set""#,
        );
        assert!(bare_set.contains("needs an `absolute`"), "{bare_set}");
        let shove_and_set = flagged(
            r#"{ "op": "filter", "input": "cutoff", "direction": "up" }"#,
            r#"{ "op": "filter", "input": "cutoff", "direction": "up", "magnitude": { "absolute": 500 } }"#,
        );
        assert!(shove_and_set.contains("relative move"), "{shove_and_set}");

        // A value outside the port's own declared range, and a symbol on a numeric port.
        let out_of_range = flagged(r#""absolute": 3"#, r#""absolute": 300"#);
        assert!(out_of_range.contains("outside"), "{out_of_range}");
        let symbol_on_a_number = flagged(
            r#""direction": "set", "magnitude": { "absolute": 3 }"#,
            r#""direction": "set", "magnitude": { "symbol": "Chord" }"#,
        );
        assert!(
            symbol_on_a_number.contains("absolute"),
            "{symbol_on_a_number}"
        );

        // Steps count an integer port; a swept scalar takes `by`/`ratio`.
        let steps_on_a_scalar = flagged(
            r#"{ "op": "filter", "input": "cutoff", "direction": "up" }"#,
            r#"{ "op": "filter", "input": "cutoff", "direction": "up", "magnitude": { "steps": 1 } }"#,
        );
        assert!(steps_on_a_scalar.contains("steps"), "{steps_on_a_scalar}");

        // A closed set has no direction.
        let pushed_enum = flagged(
            r#"{ "op": "filter", "input": "cutoff", "direction": "up" }"#,
            r#"{ "op": "snap", "input": "target", "direction": "up" }"#,
        );
        assert!(pushed_enum.contains("no direction"), "{pushed_enum}");

        // And a port with nothing to move at all.
        let unmovable = flagged(
            r#"{ "op": "filter", "input": "cutoff", "direction": "up" }"#,
            r#"{ "op": "filter", "input": "audio", "direction": "up" }"#,
        );
        assert!(unmovable.contains("no value"), "{unmovable}");
    }

    #[test]
    fn sweep_accepts_live_inputs_and_constants() {
        // `filter.cutoff` / `clock.division` / `harmony.s2` are runtime inputs; swap one row to
        // the voicer's plan-time `voices` constant to pin that constants count as the input
        // surface (matching introspect's inputs-plus-constants view).
        let json = GOOD.replace(
            r#"{ "op": "clock", "input": "division", "direction": "up", "magnitude": { "steps": 2 } }"#,
            r#"{ "op": "voicer", "input": "voices", "direction": "up" }"#,
        );
        let v = Vocabulary::parse(&json).expect("valid source");
        let errs = v.sweep(&Registry::builtin());
        assert!(errs.is_empty(), "unexpected stale rows: {errs:?}");
    }

    #[test]
    fn sweep_flags_a_departed_operator_type() {
        let json = GOOD.replace(r#""op": "clock""#, r#""op": "flanger""#);
        let v = Vocabulary::parse(&json).expect("shape is still valid");
        let errs = v.sweep(&Registry::builtin());
        assert_eq!(
            errs,
            vec!["word 'busier': operator type 'flanger' is not in the registry".to_string()]
        );
    }

    #[test]
    fn sweep_flags_a_departed_input_name() {
        let json = GOOD.replace(r#""input": "division""#, r#""input": "swing""#);
        let v = Vocabulary::parse(&json).expect("shape is still valid");
        let errs = v.sweep(&Registry::builtin());
        assert_eq!(
            errs,
            vec![
                "word 'busier': operator 'clock' has no input or constant named 'swing'"
                    .to_string()
            ]
        );
    }

    #[test]
    fn rejects_a_dangling_antonym() {
        let json = GOOD.replace(r#""antonyms": ["brighter"]"#, r#""antonyms": ["shinier"]"#);
        let err = Vocabulary::parse(&json).expect_err("dangling antonym must fail");
        assert!(err.contains("antonym 'shinier'"), "got: {err}");
    }

    #[test]
    fn rejects_a_row_with_no_moves() {
        let json = GOOD.replace(
            r#"[ { "op": "harmony", "input": "s2", "direction": "set", "magnitude": { "absolute": 3 } } ]"#,
            "[]",
        );
        let err = Vocabulary::parse(&json).expect_err("empty moves must fail");
        assert!(err.contains("'sadder' has no moves"), "got: {err}");
    }

    #[test]
    fn rejects_a_duplicate_row_but_allows_cross_section_overload() {
        // Same word twice in one section: a curation accident.
        let dup = GOOD.replace(
            r#""word": "busier", "section": "rhythmic""#,
            r#""word": "warmer", "section": "timbral""#,
        );
        let err = Vocabulary::parse(&dup).expect_err("duplicate (word, section) must fail");
        assert!(err.contains("duplicate row for 'warmer'"), "got: {err}");

        // Same word in two sections: the overloaded-word form (e.g. *darker*).
        let overloaded = GOOD.replace(
            r#""word": "busier", "section": "rhythmic""#,
            r#""word": "warmer", "section": "rhythmic""#,
        );
        Vocabulary::parse(&overloaded).expect("cross-section overload is legal");
    }

    #[test]
    fn rejects_an_unknown_section_or_field() {
        let bad_section = GOOD.replace(r#""section": "tonal""#, r#""section": "spatial""#);
        Vocabulary::parse(&bad_section).expect_err("unknown section must fail");

        let bad_field = GOOD.replace(
            r#""direction": "up" }"#,
            r#""direction": "up", "weight": 2 }"#,
        );
        Vocabulary::parse(&bad_field).expect_err("unknown field must fail");

        // The retired prose slot: a row still carrying it fails loudly rather than losing it.
        let retired = GOOD.replace(
            r#""direction": "up", "description": "it still sounds thin""#,
            r#""direction": "up", "condition": "it still sounds thin""#,
        );
        Vocabulary::parse(&retired).expect_err("`condition` is retired");

        let bad_direction = GOOD.replace(r#""direction": "up" }"#, r#""direction": "sideways" }"#);
        Vocabulary::parse(&bad_direction).expect_err("unknown direction must fail");
    }
}
