// DOM-free surface resolver for the reuben web player (ADR-0043, issue #247).
//
// An instrument's public face is its `interface` input pipes: named, engine-enforced entries
// each carrying the full quantity contract (`type`/`default`/`min`/`max`/`curve`/`unit`).
// Presentation lives in an OPTIONAL surface doc (surfaces/surface.schema.json): an ordered
// `controls[]` list binding pipes by name with `label`/`widget`/`group` and an optional
// narrower `min`/`max`. Resolving a control is therefore a thin merge — read
// `interface.inputs[bind]`, overlay the control's presentation, pick a widget — with no
// schema.json dependency and no graph archaeology.
//
// With no surface doc, a default surface is derived: one fader per wireable input pipe, in
// declaration order (exactly what the TouchOSC `boundary` generator does). Pipes a default
// cannot guess a payload for (channel-bound, bare f32_buffer, note/harmony/enum) are skipped
// with a warning naming each.
//
// The resolver is target-neutral: the Python twin (.claude/skills/control-surface) implements
// the same semantics, and both are pinned by the shared fixture
// `testdata/expected-widgets.json` (regenerated by gen-expected.mjs — ADR-0043 §9).
//
// A control bound to pipe `name` sends OSC to `/<name>/in` — the pipe node minted at
// `/<name>`, its `in` port — the same address `describe` documents. `emit`/`initial` turn a
// widget + its raw UI value into the `{address, args}` the control channel sends; render.mjs
// (on-screen) and check.mjs (headless) both route through them, so the surface and the CI
// check drive the engine over the exact same binding.

// --- vocabulary ---------------------------------------------------------------------------

// The web renderer's shipped widget kinds (ADR-0043 §5). Everything else in the surface-doc
// vocabulary — the reserved `xy-pad`/`grid`/`visualizer`/`keyboard`, or a name we don't know
// at all — is skipped loudly at resolve time.
const RENDERED_WIDGETS = new Set(["fader", "radial", "param-toggle", "note-toggle", "chord-button"]);

// Widget kinds that are their own functional class; every other rendered widget (fader,
// radial) behaves as kind "fader" — a continuous value scaled into [min, max].
const TOGGLE_KINDS = new Set(["param-toggle", "note-toggle", "chord-button"]);

// The value-backed kinds: widgets with a resting value (min/max/default) that the journal,
// the share sidecar, and applySnapshotDefaults all operate on. The hold kinds (note-toggle,
// chord-button) carry no resting state and never appear in a snapshot.
export const VALUE_KINDS = new Set(["fader", "param-toggle"]);

// The ADR-0043 §5 file-resolution candidates for the web target, most specific first:
// surfaces/<id>.web.json ?? surfaces/<id>.json (?? auto-derive, the caller's fallthrough).
// Root-relative strings — the player feeds them to fetch via its asset base, the README link
// generator joins them to the repo root. One owner so the two consumers cannot drift.
export const SURFACE_CANDIDATES = (id) => [`surfaces/${id}.web.json`, `surfaces/${id}.json`];

// The one version predicate for a parsed surface doc (throw-or-return). Callers choose the
// failure policy — the player warns and falls through to its next candidate (dark-degrade),
// the generator lets the throw kill the mint (a committed link must never carry a broken doc).
export function validateSurfaceDoc(doc) {
  if (doc?.surface_version !== 1) {
    throw new Error(`unsupported surface_version ${doc?.surface_version}`);
  }
  return doc;
}

// --- pipes ---------------------------------------------------------------------------------

/**
 * The instrument's interface input pipes as an ordered `name -> pipe` map. Only entries with
 * a `type` key are input pipes (carrying type/default/min/max/curve/unit/channel); anything
 * else under `interface.inputs` is not bindable and is ignored here.
 *
 * @param {object} instrumentDoc - a parsed instrument JSON document.
 * @returns {Map<string, object>}
 */
function inputPipes(instrumentDoc) {
  const pipes = new Map();
  for (const [name, spec] of Object.entries(instrumentDoc?.interface?.inputs ?? {})) {
    if (spec != null && typeof spec === "object" && "type" in spec) pipes.set(name, spec);
  }
  return pipes;
}

// True when the pipe declares both ends of a range — an f32_buffer is only fader-material
// when the instrument says what its numbers mean.
const hasRange = (pipe) => pipe.min != null && pipe.max != null;

/**
 * Why a default surface cannot derive a control for `pipe`, or `null` when it can (wireable:
 * `f32`, or `f32_buffer` WITH a declared min & max, and no `channel` binding).
 *
 * @param {object} pipe
 * @returns {string | null} a human-readable reason, or null when wireable.
 */
function skipReason(pipe) {
  if (pipe.channel != null) return "channel-bound (fed by an audio input channel, not OSC)";
  if (pipe.type === "f32") return null;
  if (pipe.type === "f32_buffer") {
    return hasRange(pipe) ? null : "bare f32_buffer (no declared min/max)";
  }
  return `type ${JSON.stringify(pipe.type)} (a default cannot guess its payload)`;
}

// --- labels ---------------------------------------------------------------------------------

/**
 * The pinned default-label algorithm: replace "_" with " ", split on spaces, uppercase the
 * first character of each word ("kick_step1" -> "Kick Step1", "grain_size" -> "Grain Size").
 *
 * @param {string} name - the pipe name.
 * @returns {string}
 */
function defaultLabel(name) {
  return name
    .replaceAll("_", " ")
    .split(" ")
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}

// --- control resolution ----------------------------------------------------------------------

const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));

/**
 * Resolve one surface-doc control against the instrument's pipes into a concrete widget, or
 * `null` (with a warning pushed) when the control cannot render — an unknown bind, a widget
 * this target doesn't build, a message pipe with no explicit widget, a missing payload field.
 *
 * The widget object carries exactly the pinned fixture keys: `kind`/`widget`/`bind`/`address`/
 * `label`; `group` only when set; `min`/`max`/`default` (+ `unit`/`curve` when the pipe
 * declares them) for value-backed widgets; `note`+`velocity` for a note-toggle; `degree` for
 * a chord-button. Absent keys are omitted entirely, never null.
 *
 * @param {Map<string, object>} pipes - from inputPipes().
 * @param {object} control - one surface-doc `controls[]` entry.
 * @param {string[]} warnings - collector; skip reasons are pushed here.
 * @returns {object | null}
 */
function resolveControl(pipes, control, warnings) {
  const bind = control.bind;
  const pipe = pipes.get(bind);
  if (pipe == null) {
    warnings.push(`surface control binds unknown pipe ${bind}`);
    return null;
  }

  const label = control.label ?? defaultLabel(bind);

  // Widget: the doc's choice, else inferred from the pipe type. Only a value pipe with a
  // usable range infers (to a fader); a message ("note") pipe — or anything else — has no
  // guessable payload, so with no explicit widget it is skipped loudly.
  let widget = control.widget;
  if (widget == null) {
    const value = pipe.type === "f32" || (pipe.type === "f32_buffer" && hasRange(pipe));
    if (!value) {
      warnings.push(
        `surface control ${label} (${bind}): a ${JSON.stringify(pipe.type)} pipe needs an explicit widget — skipped`,
      );
      return null;
    }
    widget = "fader";
  }
  if (!RENDERED_WIDGETS.has(widget)) {
    warnings.push(`surface control ${label} (${bind}): widget ${widget} does not render yet — skipped`);
    return null;
  }

  // kind = the widget's functional class: the toggle kinds are their own; fader/radial (and
  // any future continuous look) behave as "fader".
  const kind = TOGGLE_KINDS.has(widget) ? widget : "fader";

  const w = { kind, widget, bind, address: `/${bind}/in`, label };
  if (control.group != null) w.group = control.group;

  if (kind === "note-toggle") {
    // Payload: the constant note this button plays (required) + press velocity (default 1.0).
    if (control.note == null) {
      warnings.push(`surface control ${label} (${bind}): note-toggle needs a \`note\` — skipped`);
      return null;
    }
    w.note = control.note;
    w.velocity = control.velocity ?? 1.0;
    return w;
  }

  if (kind === "chord-button") {
    // Payload: the constant scale degree this button plays (required).
    if (control.degree == null) {
      warnings.push(`surface control ${label} (${bind}): chord-button needs a \`degree\` — skipped`);
      return null;
    }
    w.degree = control.degree;
    return w;
  }

  // Value-backed (fader/radial/param-toggle): range from the pipe, narrowable by the control
  // (the ADR-0034 §4 subset law — an override outside the pipe range is clamped into it, with
  // a warning). A pipe that declares no range falls back to [0, 1] (no committed pipe does).
  const pipeMin = pipe.min ?? 0;
  const pipeMax = pipe.max ?? 1;
  let min = pipeMin;
  let max = pipeMax;
  if (control.min != null) {
    min = clamp(control.min, pipeMin, pipeMax);
    if (min !== control.min) {
      warnings.push(
        `surface control ${label} (${bind}): min ${control.min} outside pipe range [${pipeMin}, ${pipeMax}] — clamped to ${min}`,
      );
    }
  }
  if (control.max != null) {
    max = clamp(control.max, pipeMin, pipeMax);
    if (max !== control.max) {
      warnings.push(
        `surface control ${label} (${bind}): max ${control.max} outside pipe range [${pipeMin}, ${pipeMax}] — clamped to ${max}`,
      );
    }
  }
  w.min = min;
  w.max = max;
  // The rest value: the pipe's declared default clamped into the effective (possibly
  // narrowed) range; a pipe with no default rests at min.
  w.default = pipe.default == null ? min : clamp(pipe.default, min, max);
  // unit/curve describe the QUANTITY, so they come from the pipe only — omitted, not nulled,
  // when undeclared.
  if (pipe.unit != null) w.unit = pipe.unit;
  if (pipe.curve != null) w.curve = pipe.curve;
  return w;
}

// --- layout -----------------------------------------------------------------------------

const DEFAULT_COLS = 4;
const STEP_COLS = 16; // a step lane (or a group run) lays out as a full-width row, wrapping past this

/**
 * Pack widgets into rows of varying width, preserving declaration order:
 *   - a run of consecutive `param-toggle` widgets sharing one `group` (a sequencer lane —
 *     the surface doc groups each lane's steps) becomes its own row, wrapping at STEP_COLS;
 *   - else a run of consecutive widgets sharing a `group` hint becomes its own row, wrapping
 *     at STEP_COLS;
 *   - everything else flows into a uniform grid of `cols`, flushed whenever a run interrupts.
 * So a lane's 16 steps line up as one row, each `group` (e.g. a drum channel's knobs) gets
 * its own row, and the misc controls (tempo, volumes, tone) grid up in between.
 *
 * @param {object[]} widgets
 * @param {number} [cols]
 * @returns {object[][]} rows of widgets.
 */
export function layoutRows(widgets, cols = DEFAULT_COLS) {
  const rows = [];
  let grid = [];

  const flushGrid = () => {
    for (let k = 0; k < grid.length; k += cols) rows.push(grid.slice(k, k + cols));
    grid = [];
  };
  const emitRun = (run) => {
    for (let k = 0; k < run.length; k += STEP_COLS) rows.push(run.slice(k, k + STEP_COLS));
  };

  const n = widgets.length;
  let i = 0;
  while (i < n) {
    const c = widgets[i];
    if (c.kind === "param-toggle") {
      flushGrid();
      const grp = c.group;
      let j = i;
      while (j < n && widgets[j].kind === "param-toggle" && widgets[j].group === grp) j += 1;
      emitRun(widgets.slice(i, j));
      i = j;
    } else if (c.group != null) {
      flushGrid();
      const grp = c.group;
      let j = i;
      while (j < n && widgets[j].group === grp && widgets[j].kind !== "param-toggle") j += 1;
      emitRun(widgets.slice(i, j));
      i = j;
    } else {
      grid.push(c);
      i += 1;
    }
  }
  flushGrid();
  return rows;
}

// --- public API ---------------------------------------------------------------------------

/**
 * Resolve an instrument's surface: the surface doc's controls merged with the pipes they
 * bind, or (with no doc) the auto-derived default — one fader per wireable input pipe, in
 * declaration order.
 *
 * Dark-degrade (ADR-0016): anything unresolvable — an unknown bind, an unbuilt widget kind, a
 * payload-less message pipe — is skipped with a warning naming it; only a surface doc from a
 * FUTURE format (`surface_version` != 1) refuses outright.
 *
 * @param {object} instrumentDoc - a parsed instrument JSON document.
 * @param {object | null} [surfaceDoc] - a parsed surface doc, or null for the default surface.
 * @returns {{widgets: object[], rows: object[][], warnings: string[]}}
 */
export function resolveSurface(instrumentDoc, surfaceDoc = null) {
  const warnings = [];
  const pipes = inputPipes(instrumentDoc);

  let controls;
  let cols = DEFAULT_COLS;
  if (surfaceDoc == null) {
    // Default surface: one fader per wireable pipe, declaration order; the rest warned.
    controls = [];
    for (const [name, pipe] of pipes) {
      const reason = skipReason(pipe);
      if (reason != null) warnings.push(`default surface skips pipe ${name}: ${reason}`);
      else controls.push({ bind: name, widget: "fader" });
    }
  } else {
    if (surfaceDoc.surface_version !== 1) {
      throw new Error(
        `surface doc declares surface_version ${surfaceDoc.surface_version}; this resolver knows only 1`,
      );
    }
    if (surfaceDoc.instrument !== instrumentDoc?.instrument) {
      warnings.push(
        `surface doc targets instrument ${JSON.stringify(surfaceDoc.instrument)} but the document is ${JSON.stringify(instrumentDoc?.instrument)}`,
      );
    }
    controls = surfaceDoc.controls ?? [];
    cols = surfaceDoc.cols ?? DEFAULT_COLS;
  }

  const widgets = [];
  for (const control of controls) {
    const w = resolveControl(pipes, control, warnings);
    if (w != null) widgets.push(w);
  }
  return { widgets, rows: layoutRows(widgets, cols), warnings };
}

/**
 * Build the full surface for an instrument — the public entry the web player and the headless
 * check share. A thin alias of resolveSurface: pass the surface doc when one exists
 * (`surfaces/<id>.web.json ?? surfaces/<id>.json`), or nothing for the auto-derived default.
 *
 * @param {object} instrumentDoc - a parsed instrument JSON document.
 * @param {object | null} [surfaceDoc]
 * @returns {{widgets: object[], rows: object[][], warnings: string[]}}
 */
export function buildSurface(instrumentDoc, surfaceDoc = null) {
  return resolveSurface(instrumentDoc, surfaceDoc);
}

/**
 * Fold a replayed control snapshot into a resolved surface's rest values, so the widgets
 * render showing the state they will be playing (share links, ADR-0042): each decoded
 * sidecar entry whose address matches a value-backed widget overrides that widget's
 * `default`, clamped into its range exactly as a pipe default is. Mutates the surface in
 * place, BEFORE renderSurface — the widgets seed their visuals from `default`, and
 * sendInitialDefaults/captureSnapshot then treat the replayed value as the rest baseline.
 * Entries addressing nothing on the surface, and args that aren't a bare finite number
 * (a fader/param-toggle only ever journals one raw F32), are ignored — the verbatim
 * engine replay stays the authority on what actually plays.
 *
 * @param {{widgets: object[]}} surface - from buildSurface().
 * @param {Array<{address: string, args: Array<number | string | {i32: number}>}>} entries
 *   decoded sidecar messages (codec.mjs decodeControl over each snapshot buffer).
 */
export function applySnapshotDefaults(surface, entries) {
  const byAddress = new Map();
  for (const w of surface.widgets) {
    if (!VALUE_KINDS.has(w.kind)) continue;
    const list = byAddress.get(w.address);
    if (list) list.push(w);
    else byAddress.set(w.address, [w]);
  }
  for (const { address, args } of entries) {
    const v = args?.[0];
    if (typeof v !== "number" || !Number.isFinite(v)) continue;
    for (const w of byAddress.get(address) ?? []) {
      w.default = clamp(v, w.min, w.max);
    }
  }
}

// --- binding ----------------------------------------------------------------------------

// A chord button's degree must ride the wire as an INTEGER, not a float: the `Note` OSC form
// (crates/reuben-core/src/vocab/pitch.rs) types an I32 arg as `Pitch::Degree` and an F32 arg
// as `Pitch::Absolute` (MIDI), and chord.rs only spells chords for degree pitches — a
// non-degree note is silently dropped. Bare JS numbers encode as F32 (codec.mjs), so the
// degree is marked `{i32}` (codec.mjs's explicit integer form); the gate stays F32 velocity.
// A note-toggle, by contrast, is a real absolute MIDI note and correctly stays F32.
const chordDegreeArg = (widget) => ({ i32: widget.degree });

/**
 * The load-time default send for a widget, fired once after the engine is `ready`.
 * Fader/param-toggle defaults are ALREADY in [min, max], so they are sent RAW (not scaled);
 * note/chord toggles rest at gate 0. Args are bare JS numbers (codec.mjs encodes them as F32)
 * except a chord degree, which is `{i32}` (see chordDegreeArg above).
 *
 * @param {object} widget
 * @returns {{address: string, args: Array<number | {i32: number}>}}
 */
export function initial(widget) {
  switch (widget.kind) {
    case "fader":
    case "param-toggle":
      return { address: widget.address, args: [widget.default] };
    case "note-toggle":
      return { address: widget.address, args: [widget.note, 0] };
    case "chord-button":
      return { address: widget.address, args: [chordDegreeArg(widget), 0] };
    default:
      throw new Error(`initial: unknown widget kind ${JSON.stringify(widget.kind)}`);
  }
}

/**
 * The binding fired on a UI interaction: turn a widget + its raw UI value `x` into the control
 * message to send. Used by BOTH render.mjs (on input) and check.mjs (to drive the engine).
 *   - fader / radial:  x in [0,1] is scaled into [min, max].
 *   - param-toggle:    x (0 or 1) is the payload, sent raw.
 *   - note-toggle:     `[note, velocity]` on press (x truthy), `[note, 0]` on release.
 *   - chord-button:    `[{i32: degree}, x]` — constant scale degree (I32) + gate x.
 * Args are bare JS numbers (codec.mjs encodes them as F32) except a chord degree, which is `{i32}`.
 *
 * @param {object} widget
 * @param {number} x - the widget's raw UI value.
 * @returns {{address: string, args: Array<number | {i32: number}>}}
 */
export function emit(widget, x) {
  switch (widget.kind) {
    case "fader":
      return { address: widget.address, args: [widget.min + x * (widget.max - widget.min)] };
    case "param-toggle":
      return { address: widget.address, args: [x] };
    case "note-toggle":
      return { address: widget.address, args: [widget.note, x ? widget.velocity : 0] };
    case "chord-button":
      return { address: widget.address, args: [chordDegreeArg(widget), x] };
    default:
      throw new Error(`emit: unknown widget kind ${JSON.stringify(widget.kind)}`);
  }
}
