// Unit tests for the surface pipe resolver (ADR-0043, issue #247).
//
// Pure JS, `node --test`, NO wasm and NO schema.json — the instrument's `interface` block
// carries the whole quantity contract. Two kinds of proof:
//   (1) the FIXTURE DIFF — buildSurface over each committed instrument + surface-doc pair
//       must deep-equal the committed cross-implementation oracle
//       (`testdata/expected-widgets.json`, regenerated by gen-expected.mjs). The Python twin
//       (.claude/skills/control-surface) asserts the same widget lists, so an exact
//       deep-equal here is the ADR-0043 §9 shared-fixture guarantee.
//   (2) DIRECT, human-legible assertions whose expected literals are hand-transcribed from
//       the instrument/surface JSON files — never computed with the resolver under test.
//
// Run: `cd crates/reuben-web && node --test js/surface/widget-model.test.mjs`

import test from "node:test";
import assert from "node:assert";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { buildSurface, resolveSurface, layoutRows, initial, emit } from "./widget-model.mjs";

const here = dirname(fileURLToPath(import.meta.url));

// Instruments and surface docs live at the repo root; testdata is a sibling.
const INSTRUMENT_DIR = join(here, "../../../../instruments");
const SURFACE_DIR = join(here, "../../../../surfaces");
const ORACLE_PATH = join(here, "testdata/expected-widgets.json");

const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));

const oracle = readJson(ORACLE_PATH);

// The 8 committed instrument + surface pairs (space's document lives under patches/).
const PAIRS = {
  groovebox: "groovebox.json",
  "chord-player": "chord-player.json",
  "strum-harp": "strum-harp.json",
  "euclidean-drums": "euclidean-drums.json",
  "djfilter-demo": "djfilter-demo.json",
  "good-button": "good-button.json",
  "granulator-demo": "granulator-demo.json",
  space: "patches/space.json",
};

const loadInstrument = (name) => readJson(join(INSTRUMENT_DIR, PAIRS[name]));
const loadSurfaceDoc = (name) => readJson(join(SURFACE_DIR, `${name}.json`));
const surfaceOf = (name) => buildSurface(loadInstrument(name), loadSurfaceDoc(name));

// Rows collapse to their widgets' addresses so they can be compared against the oracle,
// which stores rows as address lists.
const rowsToAddresses = (rows) => rows.map((row) => row.map((w) => w.address));

// ---------------------------------------------------------------------------------------
// (1) The fixture diff — the whole surface, exactly, for every committed pair.
// ---------------------------------------------------------------------------------------

for (const name of Object.keys(PAIRS)) {
  test(`buildSurface(${name}) deep-equals the oracle`, () => {
    const { widgets, rows, warnings } = surfaceOf(name);
    const expected = oracle[name];
    assert.ok(expected, `oracle is missing an entry for ${name}`);
    assert.deepStrictEqual(widgets, expected.widgets);
    assert.deepStrictEqual(rowsToAddresses(rows), expected.rows);
    // A committed pair must resolve clean — a warning here means instrument and surface drifted.
    assert.deepStrictEqual(warnings, [], `${name} resolves without warnings`);
  });
}

// Guard the fixture's own shape so a silently-truncated oracle can't make the diff pass.
test("oracle covers exactly the eight pairs with the documented counts", () => {
  assert.deepStrictEqual(Object.keys(oracle).sort(), Object.keys(PAIRS).sort());
  assert.strictEqual(oracle.groovebox.widgets.length, 54);
  assert.strictEqual(oracle["chord-player"].widgets.length, 9);
  assert.strictEqual(oracle["strum-harp"].widgets.length, 4);
  assert.strictEqual(oracle["euclidean-drums"].widgets.length, 25);
  assert.strictEqual(oracle["djfilter-demo"].widgets.length, 3);
  assert.strictEqual(oracle["good-button"].widgets.length, 2);
  assert.strictEqual(oracle["granulator-demo"].widgets.length, 6);
  assert.strictEqual(oracle.space.widgets.length, 2);
});

// ---------------------------------------------------------------------------------------
// (2a) Resolution merges the pipe's quantity contract — literals from the JSON by hand.
// ---------------------------------------------------------------------------------------

test("groovebox: Tempo fader carries the tempo pipe's range/default/unit on /tempo/in", () => {
  const { widgets } = surfaceOf("groovebox");
  const tempo = widgets.find((w) => w.bind === "tempo");
  // instruments/groovebox.json interface.inputs.tempo: f32, default 120, min 1, max 999, BPM.
  assert.deepStrictEqual(tempo, {
    kind: "fader",
    widget: "fader",
    bind: "tempo",
    address: "/tempo/in",
    label: "Tempo",
    min: 1,
    max: 999,
    default: 120,
    unit: "BPM",
  });
});

test("groovebox: a gate step is a param-toggle backed by its own pipe", () => {
  const { widgets } = surfaceOf("groovebox");
  const steps = widgets.filter((w) => w.kind === "param-toggle");
  assert.strictEqual(steps.length, 48);
  const k1 = widgets.find((w) => w.bind === "kick_step1");
  // interface.inputs.kick_step1: f32, default 1, min 0, max 1; surface labels it K1, group kick.
  assert.deepStrictEqual(k1, {
    kind: "param-toggle",
    widget: "param-toggle",
    bind: "kick_step1",
    address: "/kick_step1/in",
    label: "K1",
    group: "kick",
    min: 0,
    max: 1,
    default: 1,
  });
});

test("good-button: Play C is a note-toggle on /notes/in carrying note 60, velocity 1", () => {
  const { widgets } = surfaceOf("good-button");
  const play = widgets.find((w) => w.bind === "notes");
  assert.deepStrictEqual(play, {
    kind: "note-toggle",
    widget: "note-toggle",
    bind: "notes",
    address: "/notes/in",
    label: "Play C",
    note: 60,
    velocity: 1,
  });
  // The note-on carries [note, velocity]; the note-off the same note at gate 0.
  assert.deepStrictEqual(emit(play, 1), { address: "/notes/in", args: [60, 1] });
  assert.deepStrictEqual(emit(play, 0), { address: "/notes/in", args: [60, 0] });
});

test("good-button: Brightness fader binds the brightness pipe on /brightness/in", () => {
  const { widgets } = surfaceOf("good-button");
  const brightness = widgets.find((w) => w.bind === "brightness");
  // interface.inputs.brightness: f32, default 0.5, min 0, max 1 (no unit, no curve).
  assert.deepStrictEqual(brightness, {
    kind: "fader",
    widget: "fader",
    bind: "brightness",
    address: "/brightness/in",
    label: "Brightness",
    min: 0,
    max: 1,
    default: 0.5,
  });
});

test("chord-player: 7 chord-buttons share the one chord pipe with degrees 0..6", () => {
  const { widgets } = surfaceOf("chord-player");
  const chords = widgets.filter((w) => w.kind === "chord-button");
  assert.strictEqual(chords.length, 7);
  assert.ok(chords.every((w) => w.bind === "chord" && w.address === "/chord/in"));
  assert.deepStrictEqual(
    chords.map((w) => w.degree),
    [0, 1, 2, 3, 4, 5, 6],
  );
  // The first button, in full — a chord-button carries degree, never min/max/default.
  assert.deepStrictEqual(chords[0], {
    kind: "chord-button",
    widget: "chord-button",
    bind: "chord",
    address: "/chord/in",
    label: "I",
    degree: 0,
  });
});

test("euclidean-drums: radial widgets resolve to kind fader; pipe unit/curve ride along", () => {
  const { widgets } = surfaceOf("euclidean-drums");
  assert.ok(widgets.every((w) => w.kind === "fader" && w.widget === "radial"));
  const kf = widgets.find((w) => w.bind === "kick_filter");
  // interface.inputs.kick_filter: f32, default 0, min -1, max 1 — bipolar from the PIPE.
  assert.deepStrictEqual(kf, {
    kind: "fader",
    widget: "radial",
    bind: "kick_filter",
    address: "/kick_filter/in",
    label: "Kick DJ Filter",
    group: "kick",
    min: -1,
    max: 1,
    default: 0,
  });
});

test("granulator-demo: density fader inherits the pipe's exp curve and Hz unit", () => {
  const { widgets } = surfaceOf("granulator-demo");
  const density = widgets.find((w) => w.bind === "density");
  // interface.inputs.density: f32, default 30, min 1, max 200, curve exp, unit Hz.
  assert.deepStrictEqual(density, {
    kind: "fader",
    widget: "radial",
    bind: "density",
    address: "/density/in",
    label: "Density",
    min: 1,
    max: 200,
    default: 30,
    unit: "Hz",
    curve: "exp",
  });
});

// ---------------------------------------------------------------------------------------
// (2b) Default labels — replace "_" with " ", uppercase each word's first character.
// ---------------------------------------------------------------------------------------

test("a control without a label gets the pinned default label", () => {
  const inst = {
    instrument: "synth",
    interface: {
      inputs: {
        kick_step1: { type: "f32", default: 0, min: 0, max: 1 },
        grain_size: { type: "f32", default: 120, min: 5, max: 500 },
      },
    },
  };
  const doc = {
    surface_version: 1,
    instrument: "synth",
    controls: [{ bind: "kick_step1" }, { bind: "grain_size" }],
  };
  const { widgets, warnings } = resolveSurface(inst, doc);
  assert.deepStrictEqual(warnings, []);
  assert.deepStrictEqual(
    widgets.map((w) => w.label),
    ["Kick Step1", "Grain Size"],
  );
});

// ---------------------------------------------------------------------------------------
// (2c) Dark-degrade: unknown binds, unrenderable widgets, message pipes with no widget.
// ---------------------------------------------------------------------------------------

const GAIN_INST = {
  instrument: "t",
  interface: { inputs: { gain: { type: "f32", default: 0.5, min: 0, max: 1 } } },
};

test("a bind naming no pipe warns and skips the control", () => {
  const doc = {
    surface_version: 1,
    instrument: "t",
    controls: [{ bind: "nope" }, { bind: "gain" }],
  };
  const { widgets, warnings } = resolveSurface(GAIN_INST, doc);
  assert.strictEqual(widgets.length, 1);
  assert.strictEqual(widgets[0].bind, "gain");
  assert.strictEqual(warnings.length, 1);
  assert.strictEqual(warnings[0], "surface control binds unknown pipe nope");
});

test("reserved and unknown widget kinds warn (naming the control) and skip", () => {
  const doc = {
    surface_version: 1,
    instrument: "t",
    controls: [
      { bind: "gain", label: "Pad", widget: "xy-pad" }, // reserved, not built
      { bind: "gain", widget: "blob" }, // not in the vocabulary at all
      { bind: "gain" },
    ],
  };
  const { widgets, warnings } = resolveSurface(GAIN_INST, doc);
  assert.strictEqual(widgets.length, 1);
  assert.strictEqual(widgets[0].widget, "fader");
  assert.strictEqual(warnings.length, 2);
  assert.ok(warnings[0].includes("Pad") && warnings[0].includes("xy-pad"), warnings[0]);
  assert.ok(warnings[1].includes("gain") && warnings[1].includes("blob"), warnings[1]);
});

test("a note pipe with no explicit widget warns and skips (no payload to guess)", () => {
  const inst = {
    instrument: "t",
    interface: { inputs: { notes: { type: "note" } } },
  };
  const doc = { surface_version: 1, instrument: "t", controls: [{ bind: "notes" }] };
  const { widgets, warnings } = resolveSurface(inst, doc);
  assert.deepStrictEqual(widgets, []);
  assert.strictEqual(warnings.length, 1);
  assert.ok(warnings[0].includes("notes"), warnings[0]);
});

test("a note-toggle without a note (or chord-button without a degree) warns and skips", () => {
  const inst = {
    instrument: "t",
    interface: { inputs: { notes: { type: "note" } } },
  };
  const doc = {
    surface_version: 1,
    instrument: "t",
    controls: [
      { bind: "notes", widget: "note-toggle" }, // missing required `note`
      { bind: "notes", widget: "chord-button" }, // missing required `degree`
    ],
  };
  const { widgets, warnings } = resolveSurface(inst, doc);
  assert.deepStrictEqual(widgets, []);
  assert.strictEqual(warnings.length, 2);
});

// ---------------------------------------------------------------------------------------
// (2d) Range narrowing — the ADR-0034 §4 subset law: clamp into the pipe range, warn.
// ---------------------------------------------------------------------------------------

const CUTOFF_INST = {
  instrument: "t",
  interface: {
    inputs: { cutoff: { type: "f32", default: 1000, min: 100, max: 8000, unit: "Hz", curve: "exp" } },
  },
};

const resolveCutoff = (control) =>
  resolveSurface(CUTOFF_INST, { surface_version: 1, instrument: "t", controls: [control] });

test("a narrower min/max override inside the pipe range is taken verbatim, no warning", () => {
  const { widgets, warnings } = resolveCutoff({ bind: "cutoff", min: 200, max: 4000 });
  assert.deepStrictEqual(warnings, []);
  assert.deepStrictEqual(widgets[0], {
    kind: "fader",
    widget: "fader",
    bind: "cutoff",
    address: "/cutoff/in",
    label: "Cutoff",
    min: 200,
    max: 4000,
    default: 1000,
    unit: "Hz",
    curve: "exp",
  });
});

test("an override outside the pipe range is clamped INTO it, with a warning per end", () => {
  const { widgets, warnings } = resolveCutoff({ bind: "cutoff", min: 10, max: 999999 });
  assert.strictEqual(widgets[0].min, 100); // clamped up to the pipe's min
  assert.strictEqual(widgets[0].max, 8000); // clamped down to the pipe's max
  assert.strictEqual(warnings.length, 2);
  assert.ok(warnings.every((w) => w.includes("cutoff")), warnings.join("; "));
});

test("the pipe default is clamped into the effective (narrowed) [min, max]", () => {
  const { widgets, warnings } = resolveCutoff({ bind: "cutoff", min: 2000 });
  assert.deepStrictEqual(warnings, []);
  assert.strictEqual(widgets[0].min, 2000);
  assert.strictEqual(widgets[0].max, 8000);
  assert.strictEqual(widgets[0].default, 2000); // pipe default 1000 pulled up to the floor
});

test("a pipe with no declared default rests at min", () => {
  const inst = {
    instrument: "t",
    interface: { inputs: { raw: { type: "f32", min: 3, max: 9 } } },
  };
  const doc = { surface_version: 1, instrument: "t", controls: [{ bind: "raw" }] };
  const { widgets } = resolveSurface(inst, doc);
  assert.strictEqual(widgets[0].default, 3);
});

// ---------------------------------------------------------------------------------------
// (2e) Default surface (no doc): one fader per wireable pipe, declaration order.
// ---------------------------------------------------------------------------------------

test("space with NO surface doc derives 2 faders and skips the bare audio pipe", () => {
  const { widgets, rows, warnings } = buildSurface(loadInstrument("space"));
  // instruments/patches/space.json interface.inputs: `in` (bare f32_buffer — not wireable),
  // `space` (f32 0..1 default 0.35), `tone` (f32_buffer 20..20000 default 4000, exp, Hz).
  assert.deepStrictEqual(widgets, [
    {
      kind: "fader",
      widget: "fader",
      bind: "space",
      address: "/space/in",
      label: "Space",
      min: 0,
      max: 1,
      default: 0.35,
    },
    {
      kind: "fader",
      widget: "fader",
      bind: "tone",
      address: "/tone/in",
      label: "Tone",
      min: 20,
      max: 20000,
      default: 4000,
      unit: "Hz",
      curve: "exp",
    },
  ]);
  assert.deepStrictEqual(rowsToAddresses(rows), [["/space/in", "/tone/in"]]);
  assert.strictEqual(warnings.length, 1);
  assert.ok(warnings[0].includes("in"), warnings[0]);
});

test("the default surface skips a channel-bound pipe with a warning (mic-space)", () => {
  // instruments/mic-space.json has exactly one input pipe: mic (f32_buffer, channel 0).
  const { widgets, warnings } = buildSurface(readJson(join(INSTRUMENT_DIR, "mic-space.json")));
  assert.deepStrictEqual(widgets, []);
  assert.strictEqual(warnings.length, 1);
  assert.ok(warnings[0].includes("mic"), warnings[0]);
});

test("the default surface skips note/harmony/enum-typed pipes with a warning each", () => {
  const inst = {
    instrument: "t",
    interface: {
      inputs: {
        notes: { type: "note" },
        chords: { type: "harmony" },
        mode: { type: "enum" },
        gain: { type: "f32", default: 0.5, min: 0, max: 1 },
      },
    },
  };
  const { widgets, warnings } = buildSurface(inst);
  assert.strictEqual(widgets.length, 1);
  assert.strictEqual(widgets[0].bind, "gain");
  assert.strictEqual(warnings.length, 3);
  assert.ok(warnings[0].includes("notes"), warnings[0]);
  assert.ok(warnings[1].includes("chords"), warnings[1]);
  assert.ok(warnings[2].includes("mode"), warnings[2]);
});

// ---------------------------------------------------------------------------------------
// (2f) Doc envelope: surface_version gate, instrument mismatch, cols layout hint.
// ---------------------------------------------------------------------------------------

test("a surface_version other than 1 is refused outright", () => {
  const doc = { surface_version: 2, instrument: "t", controls: [] };
  assert.throws(() => resolveSurface(GAIN_INST, doc), /surface_version/);
  assert.throws(() => resolveSurface(GAIN_INST, { instrument: "t", controls: [] }), /surface_version/);
});

test("an instrument mismatch warns but still resolves", () => {
  const doc = { surface_version: 1, instrument: "other", controls: [{ bind: "gain" }] };
  const { widgets, warnings } = resolveSurface(GAIN_INST, doc);
  assert.strictEqual(widgets.length, 1);
  assert.strictEqual(warnings.length, 1);
  assert.ok(warnings[0].includes("other") && warnings[0].includes("t"), warnings[0]);
});

test("cols feeds the layout: 3 controls at cols 2 pack as [2, 1]", () => {
  const inst = {
    instrument: "t",
    interface: {
      inputs: {
        a: { type: "f32", default: 0, min: 0, max: 1 },
        b: { type: "f32", default: 0, min: 0, max: 1 },
        c: { type: "f32", default: 0, min: 0, max: 1 },
      },
    },
  };
  const doc = {
    surface_version: 1,
    instrument: "t",
    cols: 2,
    controls: [{ bind: "a" }, { bind: "b" }, { bind: "c" }],
  };
  const { rows } = resolveSurface(inst, doc);
  assert.deepStrictEqual(rowsToAddresses(rows), [["/a/in", "/b/in"], ["/c/in"]]);
});

// ---------------------------------------------------------------------------------------
// (2g) emit / initial — the pure binding used by render.mjs and check.mjs.
// ---------------------------------------------------------------------------------------

test("emit: fader scales x in [0,1] -> [min,max]", () => {
  const tempo = { kind: "fader", widget: "fader", address: "/tempo/in", min: 1, max: 999, default: 120 };
  assert.deepStrictEqual(emit(tempo, 0), { address: "/tempo/in", args: [1] });
  assert.deepStrictEqual(emit(tempo, 1), { address: "/tempo/in", args: [999] });
  assert.deepStrictEqual(emit(tempo, 0.5), { address: "/tempo/in", args: [500] }); // 1 + 0.5*998
});

test("emit: radial scales like a fader; bipolar filter maps x=0.5 -> 0", () => {
  const filter = { kind: "fader", widget: "radial", address: "/kick_filter/in", min: -1, max: 1, default: 0 };
  assert.deepStrictEqual(emit(filter, 0.5), { address: "/kick_filter/in", args: [0] });
});

test("emit: param-toggle passes x raw; note/chord carry the constant + gate", () => {
  const step = { kind: "param-toggle", widget: "param-toggle", address: "/kick_step1/in", min: 0, max: 1, default: 1 };
  assert.deepStrictEqual(emit(step, 1), { address: "/kick_step1/in", args: [1] });
  assert.deepStrictEqual(emit(step, 0), { address: "/kick_step1/in", args: [0] });

  // A pressed note-toggle sends its velocity; a released one gate 0.
  const soft = { kind: "note-toggle", widget: "note-toggle", address: "/notes/in", note: 60, velocity: 0.5 };
  assert.deepStrictEqual(emit(soft, 1), { address: "/notes/in", args: [60, 0.5] });
  assert.deepStrictEqual(emit(soft, 0), { address: "/notes/in", args: [60, 0] });

  // A chord degree rides the wire as an integer ({i32} -> Pitch::Degree); the gate stays F32.
  const chord = { kind: "chord-button", widget: "chord-button", address: "/chord/in", degree: 4 };
  assert.deepStrictEqual(emit(chord, 1), { address: "/chord/in", args: [{ i32: 4 }, 1] });
});

test("initial: fader default is raw (unscaled); note/chord rest at gate 0", () => {
  const tempo = { kind: "fader", widget: "fader", address: "/tempo/in", min: 1, max: 999, default: 120 };
  assert.deepStrictEqual(initial(tempo), { address: "/tempo/in", args: [120] });

  const step = { kind: "param-toggle", widget: "param-toggle", address: "/kick_step1/in", min: 0, max: 1, default: 1 };
  assert.deepStrictEqual(initial(step), { address: "/kick_step1/in", args: [1] });

  const play = { kind: "note-toggle", widget: "note-toggle", address: "/notes/in", note: 60, velocity: 1 };
  assert.deepStrictEqual(initial(play), { address: "/notes/in", args: [60, 0] });

  const chord = { kind: "chord-button", widget: "chord-button", address: "/chord/in", degree: 4 };
  assert.deepStrictEqual(initial(chord), { address: "/chord/in", args: [{ i32: 4 }, 0] });
});

// ---------------------------------------------------------------------------------------
// (2h) layoutRows — param-toggle lanes (keyed by group) and group runs break the grid.
// ---------------------------------------------------------------------------------------

test("layoutRows: param-toggle runs (per group) and group runs each break out of the grid", () => {
  const fader = (address, group) => ({ kind: "fader", widget: "fader", address, ...(group ? { group } : {}) });
  const toggle = (address, group) => ({
    kind: "param-toggle",
    widget: "param-toggle",
    address,
    ...(group ? { group } : {}),
  });

  const rows = layoutRows([
    fader("/a/in"),
    toggle("/k1/in", "kick"),
    toggle("/k2/in", "kick"),
    toggle("/s1/in", "snare"), // a different lane: its own run, not packed with kick
    fader("/b/in", "grp"),
    fader("/c/in", "grp"),
    fader("/d/in"),
  ]);
  assert.deepStrictEqual(rowsToAddresses(rows), [
    ["/a/in"],
    ["/k1/in", "/k2/in"],
    ["/s1/in"],
    ["/b/in", "/c/in"],
    ["/d/in"],
  ]);
});

test("layoutRows: a lane longer than 16 wraps at STEP_COLS; the plain grid wraps at cols", () => {
  const toggle = (i) => ({ kind: "param-toggle", widget: "param-toggle", address: `/s${i}/in`, group: "lane" });
  const lane = Array.from({ length: 18 }, (_, i) => toggle(i));
  const laneRows = layoutRows(lane);
  assert.deepStrictEqual(
    laneRows.map((r) => r.length),
    [16, 2],
  );

  const fader = (i) => ({ kind: "fader", widget: "fader", address: `/f${i}/in` });
  const grid = layoutRows(Array.from({ length: 5 }, (_, i) => fader(i)), 2);
  assert.deepStrictEqual(
    grid.map((r) => r.length),
    [2, 2, 1],
  );
});
