//! The generated **library index** over the available-set. see rules: authoring-library
//!
//! This module is the IO glue around the window's pure projection
//! [`reuben_api::authoring::library_index_line`]: sweep every instrument document under a
//! directory (the repo's `instruments/`, today's whole available-set), project each line through
//! the real load path, and aggregate deterministically.
//!
//! Regenerate with `cargo run -p reuben-native --example gen_library_index` after any
//! instrument change; the `library_index_is_in_sync` test fails while the committed file is
//! stale. Consumers: the web build bundles the file, the MCP sidecar serves it from the
//! checkout, the patcher skill points at it.

use std::path::{Path, PathBuf};

use reuben_api::authoring::library_index_line;
use reuben_api::FsResolver;

/// Generate the library index over every `*.json` instrument document under `instruments_dir`
/// (recursively — roles are read off the interface, never off a path, so subdirectories carry
/// no meaning). Each document loads with resolution based at its **own**
/// directory (references are relative to the referencing
/// document), `stat_only` so samples are checked for presence but never decoded. Lines sort by
/// instrument name; output is byte-deterministic. Any document that fails to load fails the
/// whole generation — a broken instrument in the available-set is a broken index, never a
/// silently missing line.
pub fn generate_library_index(instruments_dir: &Path) -> Result<String, String> {
    let mut files = Vec::new();
    collect_documents(instruments_dir, &mut files)?;
    files.sort();

    let mut lines = Vec::with_capacity(files.len());
    for path in &files {
        let source = path.display().to_string();
        // Document-scoped: the store answers for the document itself by the source as spelled, and
        // for its references from the document's own directory.
        let store = FsResolver::for_document(&source).stat_only();
        let line =
            library_index_line(&source, &store).map_err(|e| format!("{}: {e}", path.display()))?;
        lines.push(line);
    }
    // Every line leads with its instrument name, so sorting lines is sorting by name — the
    // document-derived identity, not the storage path.
    lines.sort();

    Ok(format!("{HEADER}\n{}\n", lines.join("\n")))
}

/// The committed artifact's preamble: what the file is, and how it regenerates. Part of the
/// generated bytes, so the staleness test guards it too.
const HEADER: &str = "\
# Library index

One signature line per instrument in the available-set: name — role line
(the document's `doc` first sentence), (interface input pipes) → output pipes. Trusted for
selection only — wiring facts come from `describe_patch` or the document itself. Generated:
regenerate with `cargo run -p reuben-native --example gen_library_index`; never hand-edit
(the `library_index_is_in_sync` test compares this file against a fresh generation).
";

/// Recursively collect every `*.json` path under `dir`. Read errors name the path.
fn collect_documents(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = std::fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("{}: {e}", dir.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_documents(&path, out)?;
        } else if path.extension().is_some_and(|ext| ext == "json") {
            out.push(path);
        }
    }
    Ok(())
}
